// Run against a built local server; use an existing Playwright installation.
// PLAYWRIGHT_MODULE=/absolute/path/to/playwright TEST_BASE_URL=http://127.0.0.1:3202 node --require ./tests/register.cjs tests/create-tier-list.browser.cjs
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const { expect } = require((process.env.PLAYWRIGHT_MODULE || 'playwright') + '/test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { characters } = require('../src/data/characters');
const { STORAGE_KEY, emptyDocument, createShareUrl } = require('../src/lib/tier-list-document');
const base = process.env.TEST_BASE_URL || 'http://127.0.0.1:3202';
const ids = Object.keys(characters);
const url = `${base}/create-tier-list`;
const screenshotDir = path.resolve(__dirname, '../docs/create-tier-list-qa');
fs.mkdirSync(screenshotDir, { recursive: true });

async function run() {
  const browser = await chromium.launch({ headless: true });
  const errors = [];
  const context = await browser.newContext({ viewport: { width: 1440, height: 1100 }, permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage();
  page.on('pageerror', (error) => errors.push(error.message));
  page.on('dialog', (dialog) => dialog.accept());
  const title = page.getByRole('textbox', { name: 'Tier List name' });
  const status = page.getByRole('status');
  const save = page.getByRole('button', { name: 'Save in this browser', exact: true });
  await page.goto(url);
  await expect(save).toBeEnabled();
  await title.fill('Desktop ranking 🏴‍☠️');
  const poolIds = await page.locator('[data-zone-container="pool"] [data-character-id]').evaluateAll((cards) => cards.map((card) => card.dataset.characterId));
  for (const id of poolIds.slice(0, 2)) {
    await page.locator(`[data-character-id="${id}"] button[aria-label^="Choose"]`).click();
    await page.getByRole('dialog').getByRole('button', { name: 'GOD', exact: true }).click();
  }
  const god = page.locator('[data-zone-container="god"]');
  await expect(god.locator('[data-character-id]')).toHaveCount(2);
  // Preserve existing native drag ordering and move-back behavior.
  await god.locator(`[data-character-id="${poolIds[1]}"] > div`).dragTo(god.locator(`[data-character-id="${poolIds[0]}"]`), { targetPosition: { x: 3, y: 40 } });
  assert.deepEqual(await god.locator('[data-character-id]').evaluateAll((cards) => cards.map((card) => card.dataset.characterId)), [poolIds[1], poolIds[0]]);
  await save.click();
  await expect(status).toHaveText('Saved in this browser.');
  const stored = await page.evaluate((key) => localStorage.getItem(key), STORAGE_KEY);
  const saved = JSON.parse(stored);
  assert.deepEqual(saved.tiers.god, [poolIds[1], poolIds[0]]);
  await page.reload();
  await expect(title).toHaveValue(saved.title);
  await expect(god.locator('[data-character-id]')).toHaveCount(2);
  await page.getByRole('button', { name: 'Create share link', exact: true }).click();
  const linkInput = page.getByRole('textbox', { name: 'Share link', exact: true });
  await expect(linkInput).toBeVisible();
  const shareUrl = await linkInput.inputValue();
  assert.ok(shareUrl.length < 8000);
  await page.getByRole('button', { name: 'Copy link', exact: true }).click();
  await expect(status).toHaveText('Share link copied.');
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), shareUrl);
  await page.evaluate(() => Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: () => Promise.reject(new Error('denied')) } }));
  await page.getByRole('button', { name: 'Copy link', exact: true }).click();
  await expect(status).toContainText('copy it manually');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download file', exact: true }).click();
  const download = await downloadPromise;
  const file = await download.path();
  assert.deepEqual(JSON.parse(fs.readFileSync(file, 'utf8')), saved);
  await page.evaluate(() => scrollTo(0, 0));
  await page.screenshot({ path: path.join(screenshotDir, 'desktop.png'), fullPage: true });
  await page.getByRole('link', { name: 'About', exact: true }).click();
  await expect(page).toHaveURL(/\/about$/);
  await page.goBack();
  await expect(title).toHaveValue(saved.title);
  console.log(`PASS desktop save/reload, placement/native reorder, snapshot (${shareUrl.length} chars), clipboard success/failure, download`);

  await title.fill('Unsaved desktop edit');
  await page.getByRole('button', { name: 'Restore browser save' }).click();
  await expect(page.getByRole('group', { name: 'Unsaved changes' })).toBeVisible();
  await page.getByRole('button', { name: 'Keep editing' }).click();
  await expect(title).toHaveValue('Unsaved desktop edit');
  await page.getByRole('button', { name: 'Restore browser save' }).click();
  await page.getByRole('button', { name: 'Discard edits & load list' }).click();
  await expect(title).toHaveValue(saved.title);

  // New link delivered in-place must preserve dirty edits until explicitly accepted.
  const other = emptyDocument(ids); other.title = 'Other shared snapshot'; other.tiers.ss = [ids[3]]; other.pool = ids.filter((id) => id !== ids[3]);
  const otherUrl = await createShareUrl(other, url);
  await title.fill('Keep me');
  await page.evaluate((hash) => { location.hash = hash; }, new URL(otherUrl).hash);
  await expect(page.getByRole('group', { name: 'Unsaved changes' })).toBeVisible();
  await expect(title).toHaveValue('Keep me');
  await page.getByRole('button', { name: 'Keep editing' }).click();
  await expect(page).toHaveURL(url);
  await save.click();
  await page.evaluate((hash) => { location.hash = hash; }, new URL(otherUrl).hash);
  await expect(page.getByRole('button', { name: 'Copy & edit my own list' })).toBeVisible();
  await expect(title).toHaveValue(other.title);
  await page.goBack();
  await expect(title).toHaveValue('Keep me');
  await page.goForward();
  await expect(title).toHaveValue(other.title);
  await expect(title).toHaveAttribute('readonly', '');
  await expect(page.getByRole('button', { name: 'Reset', exact: true })).toBeDisabled();
  await expect(page.locator('[data-zone-container="ss"] button[aria-label^="Choose"]')).toBeDisabled();
  assert.equal(JSON.parse(await page.evaluate((key) => localStorage.getItem(key), STORAGE_KEY)).title, 'Keep me');
  await page.getByRole('button', { name: 'Copy & edit my own list' }).click();
  await expect(page).toHaveURL(url);
  await title.fill('My editable copy');
  assert.equal(JSON.parse(await page.evaluate((key) => localStorage.getItem(key), STORAGE_KEY)).title, 'Keep me');
  await save.click();
  await page.reload();
  await expect(title).toHaveValue('My editable copy');
  console.log('PASS restore confirmation, shared snapshot read-only, copy/edit without changing browser save, hash/back/forward, saved copy reload');

  // Invalid data must never touch the browser save or current edits.
  const copySave = await page.evaluate((key) => localStorage.getItem(key), STORAGE_KEY);
  await title.fill('Still editing');
  await page.evaluate(() => { location.hash = '#tier=v1.bad%'; });
  await expect(status).toContainText('Could not open shared tier list');
  await expect(title).toHaveValue('Still editing');
  assert.equal(await page.evaluate((key) => localStorage.getItem(key), STORAGE_KEY), copySave);
  const importInput = page.locator('input[type="file"]');
  await importInput.setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{') });
  await expect(status).toContainText('Could not import');
  await expect(title).toHaveValue('Still editing');
  await importInput.setInputFiles({ name: 'list.json', mimeType: 'application/json', buffer: Buffer.from(stored) });
  await expect(page.getByRole('group', { name: 'Unsaved changes' })).toBeVisible();
  await page.getByRole('button', { name: 'Discard edits & load list' }).click();
  await expect(title).toHaveValue(saved.title);
  await expect(page.getByText('Unsaved changes', { exact: true })).toBeVisible();
  assert.equal(await page.evaluate((key) => localStorage.getItem(key), STORAGE_KEY), copySave);
  await save.click();
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('full', 'QuotaExceededError'); }; });
  await title.fill('Quota failure list');
  await save.click();
  await expect(status).toContainText('storage blocked or full');
  await expect(title).toHaveValue('Quota failure list');
  assert.equal(await page.evaluate((key) => localStorage.getItem(key), STORAGE_KEY), stored);
  console.log('PASS malformed hash/file, import confirmation/unsaved state, quota failure preserving saved list');

  const blocked = await browser.newContext();
  await blocked.addInitScript(() => { Storage.prototype.getItem = () => { throw new DOMException('blocked', 'SecurityError'); }; Storage.prototype.setItem = () => { throw new DOMException('blocked', 'SecurityError'); }; });
  const blockedPage = await blocked.newPage();
  await blockedPage.goto(url);
  await expect(blockedPage.getByRole('button', { name: 'Save in this browser', exact: true })).toBeEnabled();
  await expect(blockedPage.getByRole('status')).toContainText('storage is unavailable');
  await blockedPage.getByRole('textbox', { name: 'Tier List name' }).fill('Storage unavailable');
  await blockedPage.getByRole('button', { name: 'Save in this browser', exact: true }).click();
  await expect(blockedPage.getByRole('status')).toContainText('Could not save');
  await blockedPage.getByRole('button', { name: 'Create share link', exact: true }).click();
  await expect(blockedPage.getByRole('textbox', { name: 'Share link', exact: true })).toBeVisible();
  await blocked.close();
  console.log('PASS unavailable storage does not block editing/share');

  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 1, isMobile: true, hasTouch: true });
  const mobilePage = await mobile.newPage();
  mobilePage.on('pageerror', (error) => errors.push(error.message));
  await mobilePage.goto(shareUrl);
  await expect(mobilePage.getByRole('button', { name: 'Copy & edit my own list' })).toBeVisible();
  await expect(mobilePage.getByRole('textbox', { name: 'Tier List name' })).toHaveValue(saved.title);
  await mobilePage.screenshot({ path: path.join(screenshotDir, 'mobile-shared.png'), fullPage: true });
  await mobilePage.getByRole('button', { name: 'Copy & edit my own list' }).click();
  const mobileGod = mobilePage.locator('[data-zone-container="god"]');
  await mobileGod.locator(`[data-character-id="${poolIds[0]}"] button[aria-label^="Choose"]`).tap();
  await mobilePage.getByRole('dialog').getByRole('button', { name: 'SS', exact: true }).tap();
  await expect(mobilePage.locator('[data-zone-container="ss"] [data-character-id]')).toHaveCount(1);
  await mobilePage.getByRole('button', { name: 'Save in this browser', exact: true }).click();
  await mobilePage.reload();
  await expect(mobilePage.locator('[data-zone-container="ss"] [data-character-id]')).toHaveCount(1);
  await mobilePage.getByRole('textbox', { name: 'Search characters' }).fill('unfindable character');
  await expect(mobilePage.getByText('No unranked characters match your search and filters.')).toBeVisible();
  await mobilePage.getByRole('textbox', { name: 'Search characters' }).fill('');
  assert.ok(await mobilePage.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  // Exercise the existing touch drag handle, including pointer capture cleanup.
  const handle = mobilePage.locator(`[data-zone-container="ss"] [data-character-id="${poolIds[0]}"] button[aria-label^="Drag"]`);
  await handle.scrollIntoViewIfNeeded();
  const start = await handle.boundingBox();
  const target = await mobilePage.locator('[data-zone-container="s"]').boundingBox();
  const cdp = await mobile.newCDPSession(mobilePage);
  const touch = (x, y) => ({ x, y, id: 1, radiusX: 8, radiusY: 8, force: 1 });
  const from = touch(start.x + start.width / 2, start.y + start.height / 2);
  const to = touch(target.x + target.width / 2, target.y + target.height / 2);
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [from] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [to] });
  await cdp.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] });
  await expect(mobilePage.locator('[data-zone-container="s"] [data-character-id]')).toHaveCount(1);
  await expect(mobilePage.locator('[data-zone-container="ss"] [data-character-id]')).toHaveCount(0);
  assert.equal(await mobilePage.evaluate(() => document.body.style.overflow), '');
  await mobilePage.getByRole('button', { name: 'Save in this browser', exact: true }).click();
  await mobilePage.reload();
  await expect(mobilePage.locator('[data-zone-container="s"] [data-character-id]')).toHaveCount(1);
  await mobilePage.evaluate(() => scrollTo(0, 0));
  await mobilePage.screenshot({ path: path.join(screenshotDir, 'mobile-edit.png'), fullPage: true });
  console.log('PASS mobile share view/copy/tap and touch-drag placement/reload/search/no horizontal overflow');
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS no browser page errors');
}
run().catch((error) => { console.error(error); process.exit(1); });
