/* This file is generated by scripts/medal-importer/import.mjs. */

import type { Medal } from "./types";

export const medals = [
  {
    "id": "future-where-im-the-most-free",
    "name": "Future Where I'm the Most Free Medal",
    "category": "character",
    "uniqueTrait": "When attacking an enemy with a Normal Attack, 30% chance to: Reduce the cooldown time of Skill 2 by 3%.",
    "tags": [
      {
        "id": "egghead",
        "name": "Egghead"
      },
      {
        "id": "bonney-pirates",
        "name": "Bonney Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "royalty-former-royalty",
        "name": "Royalty / Former Royalty"
      },
      {
        "id": "worst-generation",
        "name": "Worst Generation"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "tempest-kick-white-thunder",
    "name": "Tempest Kick: White Thunder Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 70% or more: Boost the cooldown reduction speed of Skill 1 by 13%.",
    "tags": [
      {
        "id": "egghead",
        "name": "Egghead"
      },
      {
        "id": "cipher-pol-former-cipher-pol",
        "name": "Cipher Pol / Former Cipher Pol"
      },
      {
        "id": "zoan",
        "name": "Zoan"
      },
      {
        "id": "intelligence-agent",
        "name": "Intelligence Agent"
      },
      {
        "id": "six-powers",
        "name": "Six Powers"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "warrior-of-liberation",
    "name": "Warrior of Liberation Medal",
    "category": "event",
    "uniqueTrait": "When the equipped character is character type \"Captain\": Increase Normal Attack damage dealt by 3%.",
    "tags": [
      {
        "id": "egghead",
        "name": "Egghead"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "zoan",
        "name": "Zoan"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "the-four-emperors",
        "name": "The Four Emperors"
      },
      {
        "id": "blood-brothers",
        "name": "Blood Brothers"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "bonneys-daddy",
    "name": "Bonney's Daddy Medal",
    "category": "event",
    "uniqueTrait": "When you Knockback an enemy: Reduce the cooldown time of Skill 2 by 5%.",
    "tags": [
      {
        "id": "revolutionary-army",
        "name": "Revolutionary Army"
      },
      {
        "id": "the-seven-warlords-of-the-sea-former-warlords-of-the-sea",
        "name": "The Seven Warlords of the Sea / Former Warlords of the Sea"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "royalty-former-royalty",
        "name": "Royalty / Former Royalty"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "hand-pistol-yellow-lotus",
    "name": "Hand Pistol Yellow Lotus Medal",
    "category": "character",
    "uniqueTrait": "When an enemy begins capturing one of your team's Treasure Areas: Reduce the cooldown time of Skill 1 by 3%.",
    "tags": [
      {
        "id": "egghead",
        "name": "Egghead"
      },
      {
        "id": "cipher-pol-former-cipher-pol",
        "name": "Cipher Pol / Former Cipher Pol"
      },
      {
        "id": "zoan",
        "name": "Zoan"
      },
      {
        "id": "intelligence-agent",
        "name": "Intelligence Agent"
      },
      {
        "id": "six-powers",
        "name": "Six Powers"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "clawed"
    ]
  },
  {
    "id": "st-marcus-mars",
    "name": "St. Marcus Mars Medal",
    "category": "character",
    "uniqueTrait": "When in the area around your enemy's Treasure: Reduce damage received by 5%.",
    "tags": [
      {
        "id": "egghead",
        "name": "Egghead"
      },
      {
        "id": "world-noble",
        "name": "World Noble"
      },
      {
        "id": "the-five-elders",
        "name": "The Five Elders"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "hp"
    ]
  },
  {
    "id": "kyros",
    "name": "Kyros Medal",
    "category": "character",
    "uniqueTrait": "When in the Treasure Area: Reduce damage received by 5%.",
    "tags": [
      {
        "id": "dressrosa",
        "name": "Dressrosa"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "hp"
    ]
  },
  {
    "id": "gungnir",
    "name": "Gungnir Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 70% or more: Increase damage dealt by 5%.",
    "tags": [
      {
        "id": "dressrosa",
        "name": "Dressrosa"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "giant",
        "name": "Giant"
      },
      {
        "id": "straw-hat-fleet",
        "name": "Straw Hat Fleet"
      }
    ],
    "nativeTraits": [
      "crit",
      "def",
      "hp"
    ]
  },
  {
    "id": "stone-stone",
    "name": "Stone Stone Medal",
    "category": "character",
    "uniqueTrait": "When in the area around your captured Treasure: Reduce damage received by 5%.",
    "tags": [
      {
        "id": "dressrosa",
        "name": "Dressrosa"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "pica-army",
        "name": "Pica Army"
      },
      {
        "id": "don-quixote-family",
        "name": "Don Quixote Family"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "capture-block"
    ]
  },
  {
    "id": "the-wings",
    "name": "The Wings Medal",
    "category": "character",
    "uniqueTrait": "When you are Downed: Reduce the cooldown time of Skill 2 by 4%.",
    "tags": [
      {
        "id": "land-of-wano",
        "name": "Land of Wano"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "combatant",
        "name": "Combatant"
      },
      {
        "id": "royalty-former-royalty",
        "name": "Royalty / Former Royalty"
      },
      {
        "id": "great-grade-sword-wielder",
        "name": "Great Grade Sword Wielder"
      },
      {
        "id": "worst-generation",
        "name": "Worst Generation"
      }
    ],
    "nativeTraits": [
      "hp",
      "crit"
    ],
    "statusReductions": [
      "aflame"
    ]
  },
  {
    "id": "sew-sew",
    "name": "Sew-Sew Medal",
    "category": "event",
    "uniqueTrait": "When you capture the Treasure: Reduce the cooldown time of Skill 2 by 6%.",
    "tags": [
      {
        "id": "dressrosa",
        "name": "Dressrosa"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "straw-hat-fleet",
        "name": "Straw Hat Fleet"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "luffy",
    "name": "Luffy Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, CRIT: Boosted by 40% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "blood-brothers",
        "name": "Blood Brothers"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "zoro",
    "name": "Zoro Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 30% or less: CRIT: Boosted by 40% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "combatant",
        "name": "Combatant"
      },
      {
        "id": "great-grade-sword-wielder",
        "name": "Great Grade Sword Wielder"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "usopp",
    "name": "Usopp Medal",
    "category": "character",
    "uniqueTrait": "When there are 60 seconds or less remaining: Boost capture speed by 6%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "sharp-shooter",
        "name": "Sharp Shooter"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk"
    ],
    "statusReductions": [
      "aflame"
    ]
  },
  {
    "id": "sanji",
    "name": "Sanji Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, Reduce the cooldown time of Skill 1 by 4%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "cook",
        "name": "Cook"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "nami",
    "name": "Nami Medal",
    "category": "character",
    "uniqueTrait": "When you capture the Treasure: Reduce the cooldown time of Skill 1 by 4%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "navigator",
        "name": "Navigator"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "chopper",
    "name": "Chopper Medal",
    "category": "character",
    "uniqueTrait": "When your team has less Treasure secured: Boost the cooldown reduction speed of Skill 1 by 7%.",
    "tags": [
      {
        "id": "the-grand-line",
        "name": "The Grand Line"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "zoan",
        "name": "Zoan"
      },
      {
        "id": "doctor",
        "name": "Doctor"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "robin",
    "name": "Robin Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, SPD: Boosted by 2% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "sky-island-lrll",
        "name": "Sky Island / LRLL"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "baroque-works-former-baroque-works",
        "name": "Baroque Works / Former Baroque Works"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "archaeologist",
        "name": "Archaeologist"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "butchie",
    "name": "Butchie Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 30% or less: SPD: Boosted by 2% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "black-cat-pirates",
        "name": "Black Cat Pirates"
      },
      {
        "id": "combatant",
        "name": "Combatant"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "tremor"
    ]
  },
  {
    "id": "koby",
    "name": "Koby Medal",
    "category": "character",
    "uniqueTrait": "When your allies are near the Treasure area where you are at: Boost capture speed by 6%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "stun"
    ]
  },
  {
    "id": "helmeppo",
    "name": "Helmeppo Medal",
    "category": "character",
    "uniqueTrait": "When you capture the Treasure: SPD: Boosted by 2% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "cabaji",
    "name": "Cabaji Medal",
    "category": "character",
    "uniqueTrait": "When your team has more Treasure secured: Boost capture speed by 6%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "buggy-pirates",
        "name": "Buggy Pirates"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "alvida",
    "name": "Alvida Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 7% or less: Increase Treasure Gauge recovery amount.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "the-alvida-pirates",
        "name": "The Alvida Pirates"
      },
      {
        "id": "captain",
        "name": "Captain"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "stun"
    ]
  },
  {
    "id": "higuma",
    "name": "Higuma Medal",
    "category": "character",
    "uniqueTrait": "When Respawned: SPD: Boosted by 2% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "kuroobi",
    "name": "Kuroobi Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 70% or more: Boost the cooldown reduction speed of Skill 1 by 10%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "arlong-pirates",
        "name": "Arlong Pirates"
      },
      {
        "id": "fish-man",
        "name": "Fish-Man"
      },
      {
        "id": "fish-man-karate",
        "name": "Fish-Man Karate"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "johnny",
    "name": "Johnny Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 30% or less: Boost capture speed by 6%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "bounty-hunter",
        "name": "Bounty Hunter"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "morgan",
    "name": "Morgan Medal",
    "category": "character",
    "uniqueTrait": "When there are 60 seconds or less remaining: CRIT: Boosted by 40% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "navy",
        "name": "Navy"
      },
      {
        "id": "navy-captain",
        "name": "Navy Captain"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "choo",
    "name": "Choo Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, CRIT: Boosted by 90% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "arlong-pirates",
        "name": "Arlong Pirates"
      },
      {
        "id": "fish-man",
        "name": "Fish-Man"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "yosaku",
    "name": "Yosaku Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 7% or less: Increase the Treasure Gauge amount when you capture Treasure.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "bounty-hunter",
        "name": "Bounty Hunter"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "hachi",
    "name": "Hachi Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 50% or less: Boost the cooldown reduction speed of Skill 1 by 10%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "arlong-pirates",
        "name": "Arlong Pirates"
      },
      {
        "id": "fish-man",
        "name": "Fish-Man"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "django",
    "name": "Django Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 70% or more: Boost the cooldown reduction speed of Skill 1 by 7%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "black-cat-pirates",
        "name": "Black Cat Pirates"
      },
      {
        "id": "captain",
        "name": "Captain"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "kuro",
    "name": "Kuro Medal",
    "category": "character",
    "uniqueTrait": "When your team has more Treasure secured: Boost the cooldown reduction speed of Skill 1 by 10%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "black-cat-pirates",
        "name": "Black Cat Pirates"
      },
      {
        "id": "captain",
        "name": "Captain"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "gin",
    "name": "Gin Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, Reduce the cooldown time of Skill 1 by 6%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "krieg-s-pirate-armada",
        "name": "Krieg's Pirate Armada"
      },
      {
        "id": "combatant",
        "name": "Combatant"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "don-krieg",
    "name": "Don Krieg Medal",
    "category": "character",
    "uniqueTrait": "When an ally is KO'd (not including you): Reduce the cooldown time of Skill 1 by 3%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "krieg-s-pirate-armada",
        "name": "Krieg's Pirate Armada"
      },
      {
        "id": "captain",
        "name": "Captain"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "poison"
    ]
  },
  {
    "id": "zeff",
    "name": "Zeff Medal",
    "category": "character",
    "uniqueTrait": "When there are 60 seconds or less remaining: CRIT: Boosted by 90% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "cook",
        "name": "Cook"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "yasopp",
    "name": "Yasopp Medal",
    "category": "character",
    "uniqueTrait": "When you capture the Treasure: Reduce the cooldown time of Skill 1 by 8%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "red-haired-pirates",
        "name": "Red-Haired Pirates"
      },
      {
        "id": "sharp-shooter",
        "name": "Sharp Shooter"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "buggy",
    "name": "Buggy Medal",
    "category": "character",
    "uniqueTrait": "When your allies are near the Treasure area where you are at: Boost the cooldown reduction speed of Skill 1 by 10%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "buggy-pirates",
        "name": "Buggy Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "roger-pirates-ex-roger-pirates",
        "name": "Roger Pirates / Ex-Roger Pirates"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "saw",
    "name": "Saw Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, CRIT: Boosted by 120% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "arlong-pirates",
        "name": "Arlong Pirates"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "fish-man",
        "name": "Fish-Man"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "shanks",
    "name": "Shanks Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 70% or more: Boost the cooldown reduction speed of dodge by 13%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "red-haired-pirates",
        "name": "Red-Haired Pirates"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "roger-pirates-ex-roger-pirates",
        "name": "Roger Pirates / Ex-Roger Pirates"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "kaya",
    "name": "Kaya Medal",
    "category": "character",
    "uniqueTrait": "When there are 60 seconds or less remaining: Boost the cooldown reduction speed of Skill 2 by 13%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  }
] as const satisfies readonly Medal[];
