/* This file is generated by scripts/medal-importer/import.mjs. */

import type { Medal } from "./types";

export const medals = [
  {
    "id": "future-where-im-the-most-free",
    "name": "Future Where I'm the Most Free Medal",
    "category": "character",
    "uniqueTrait": "When attacking an enemy with a Normal Attack, 30% chance to: Reduce the cooldown time of Skill 2 by 3%.",
    "tags": [
      {
        "id": "egghead",
        "name": "Egghead"
      },
      {
        "id": "bonney-pirates",
        "name": "Bonney Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "royalty-former-royalty",
        "name": "Royalty / Former Royalty"
      },
      {
        "id": "worst-generation",
        "name": "Worst Generation"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "tempest-kick-white-thunder",
    "name": "Tempest Kick: White Thunder Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 70% or more: Boost the cooldown reduction speed of Skill 1 by 13%.",
    "tags": [
      {
        "id": "egghead",
        "name": "Egghead"
      },
      {
        "id": "cipher-pol-former-cipher-pol",
        "name": "Cipher Pol / Former Cipher Pol"
      },
      {
        "id": "zoan",
        "name": "Zoan"
      },
      {
        "id": "intelligence-agent",
        "name": "Intelligence Agent"
      },
      {
        "id": "six-powers",
        "name": "Six Powers"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "warrior-of-liberation",
    "name": "Warrior of Liberation Medal",
    "category": "event",
    "uniqueTrait": "When the equipped character is character type \"Captain\": Increase Normal Attack damage dealt by 3%.",
    "tags": [
      {
        "id": "egghead",
        "name": "Egghead"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "zoan",
        "name": "Zoan"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "the-four-emperors",
        "name": "The Four Emperors"
      },
      {
        "id": "blood-brothers",
        "name": "Blood Brothers"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "bonneys-daddy",
    "name": "Bonney's Daddy Medal",
    "category": "event",
    "uniqueTrait": "When you Knockback an enemy: Reduce the cooldown time of Skill 2 by 5%.",
    "tags": [
      {
        "id": "revolutionary-army",
        "name": "Revolutionary Army"
      },
      {
        "id": "the-seven-warlords-of-the-sea-former-warlords-of-the-sea",
        "name": "The Seven Warlords of the Sea / Former Warlords of the Sea"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "royalty-former-royalty",
        "name": "Royalty / Former Royalty"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "hand-pistol-yellow-lotus",
    "name": "Hand Pistol Yellow Lotus Medal",
    "category": "character",
    "uniqueTrait": "When an enemy begins capturing one of your team's Treasure Areas: Reduce the cooldown time of Skill 1 by 3%.",
    "tags": [
      {
        "id": "egghead",
        "name": "Egghead"
      },
      {
        "id": "cipher-pol-former-cipher-pol",
        "name": "Cipher Pol / Former Cipher Pol"
      },
      {
        "id": "zoan",
        "name": "Zoan"
      },
      {
        "id": "intelligence-agent",
        "name": "Intelligence Agent"
      },
      {
        "id": "six-powers",
        "name": "Six Powers"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "clawed"
    ]
  },
  {
    "id": "st-marcus-mars",
    "name": "St. Marcus Mars Medal",
    "category": "character",
    "uniqueTrait": "When in the area around your enemy's Treasure: Reduce damage received by 5%.",
    "tags": [
      {
        "id": "egghead",
        "name": "Egghead"
      },
      {
        "id": "world-noble",
        "name": "World Noble"
      },
      {
        "id": "the-five-elders",
        "name": "The Five Elders"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "hp"
    ]
  },
  {
    "id": "kyros",
    "name": "Kyros Medal",
    "category": "character",
    "uniqueTrait": "When in the Treasure Area: Reduce damage received by 5%.",
    "tags": [
      {
        "id": "dressrosa",
        "name": "Dressrosa"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "hp"
    ]
  },
  {
    "id": "gungnir",
    "name": "Gungnir Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 70% or more: Increase damage dealt by 5%.",
    "tags": [
      {
        "id": "dressrosa",
        "name": "Dressrosa"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "giant",
        "name": "Giant"
      },
      {
        "id": "straw-hat-fleet",
        "name": "Straw Hat Fleet"
      }
    ],
    "nativeTraits": [
      "crit",
      "def",
      "hp"
    ]
  },
  {
    "id": "stone-stone",
    "name": "Stone Stone Medal",
    "category": "character",
    "uniqueTrait": "When in the area around your captured Treasure: Reduce damage received by 5%.",
    "tags": [
      {
        "id": "dressrosa",
        "name": "Dressrosa"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "pica-army",
        "name": "Pica Army"
      },
      {
        "id": "don-quixote-family",
        "name": "Don Quixote Family"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "capture-block"
    ]
  },
  {
    "id": "the-wings",
    "name": "The Wings Medal",
    "category": "character",
    "uniqueTrait": "When you are Downed: Reduce the cooldown time of Skill 2 by 4%.",
    "tags": [
      {
        "id": "land-of-wano",
        "name": "Land of Wano"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "combatant",
        "name": "Combatant"
      },
      {
        "id": "royalty-former-royalty",
        "name": "Royalty / Former Royalty"
      },
      {
        "id": "great-grade-sword-wielder",
        "name": "Great Grade Sword Wielder"
      },
      {
        "id": "worst-generation",
        "name": "Worst Generation"
      }
    ],
    "nativeTraits": [
      "hp",
      "crit"
    ],
    "statusReductions": [
      "aflame"
    ]
  },
  {
    "id": "sew-sew",
    "name": "Sew-Sew Medal",
    "category": "event",
    "uniqueTrait": "When you capture the Treasure: Reduce the cooldown time of Skill 2 by 6%.",
    "tags": [
      {
        "id": "dressrosa",
        "name": "Dressrosa"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "straw-hat-fleet",
        "name": "Straw Hat Fleet"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "luffy",
    "name": "Luffy Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, CRIT: Boosted by 40% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "blood-brothers",
        "name": "Blood Brothers"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "zoro",
    "name": "Zoro Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 30% or less: CRIT: Boosted by 40% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "combatant",
        "name": "Combatant"
      },
      {
        "id": "great-grade-sword-wielder",
        "name": "Great Grade Sword Wielder"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "usopp",
    "name": "Usopp Medal",
    "category": "character",
    "uniqueTrait": "When there are 60 seconds or less remaining: Boost capture speed by 6%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "sharp-shooter",
        "name": "Sharp Shooter"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk"
    ],
    "statusReductions": [
      "aflame"
    ]
  },
  {
    "id": "sanji",
    "name": "Sanji Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, Reduce the cooldown time of Skill 1 by 4%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "cook",
        "name": "Cook"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "nami",
    "name": "Nami Medal",
    "category": "character",
    "uniqueTrait": "When you capture the Treasure: Reduce the cooldown time of Skill 1 by 4%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "navigator",
        "name": "Navigator"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "chopper",
    "name": "Chopper Medal",
    "category": "character",
    "uniqueTrait": "When your team has less Treasure secured: Boost the cooldown reduction speed of Skill 1 by 7%.",
    "tags": [
      {
        "id": "the-grand-line",
        "name": "The Grand Line"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "zoan",
        "name": "Zoan"
      },
      {
        "id": "doctor",
        "name": "Doctor"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "robin",
    "name": "Robin Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, SPD: Boosted by 2% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "sky-island-lrll",
        "name": "Sky Island / LRLL"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "baroque-works-former-baroque-works",
        "name": "Baroque Works / Former Baroque Works"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "archaeologist",
        "name": "Archaeologist"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "butchie",
    "name": "Butchie Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 30% or less: SPD: Boosted by 2% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "black-cat-pirates",
        "name": "Black Cat Pirates"
      },
      {
        "id": "combatant",
        "name": "Combatant"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "tremor"
    ]
  },
  {
    "id": "koby",
    "name": "Koby Medal",
    "category": "character",
    "uniqueTrait": "When your allies are near the Treasure area where you are at: Boost capture speed by 6%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "stun"
    ]
  },
  {
    "id": "helmeppo",
    "name": "Helmeppo Medal",
    "category": "character",
    "uniqueTrait": "When you capture the Treasure: SPD: Boosted by 2% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "cabaji",
    "name": "Cabaji Medal",
    "category": "character",
    "uniqueTrait": "When your team has more Treasure secured: Boost capture speed by 6%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "buggy-pirates",
        "name": "Buggy Pirates"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "alvida",
    "name": "Alvida Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 7% or less: Increase Treasure Gauge recovery amount.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "the-alvida-pirates",
        "name": "The Alvida Pirates"
      },
      {
        "id": "captain",
        "name": "Captain"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "stun"
    ]
  },
  {
    "id": "higuma",
    "name": "Higuma Medal",
    "category": "character",
    "uniqueTrait": "When Respawned: SPD: Boosted by 2% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "kuroobi",
    "name": "Kuroobi Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 70% or more: Boost the cooldown reduction speed of Skill 1 by 10%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "arlong-pirates",
        "name": "Arlong Pirates"
      },
      {
        "id": "fish-man",
        "name": "Fish-Man"
      },
      {
        "id": "fish-man-karate",
        "name": "Fish-Man Karate"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "johnny",
    "name": "Johnny Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 30% or less: Boost capture speed by 6%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "bounty-hunter",
        "name": "Bounty Hunter"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "morgan",
    "name": "Morgan Medal",
    "category": "character",
    "uniqueTrait": "When there are 60 seconds or less remaining: CRIT: Boosted by 40% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "navy",
        "name": "Navy"
      },
      {
        "id": "navy-captain",
        "name": "Navy Captain"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "choo",
    "name": "Choo Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, CRIT: Boosted by 90% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "arlong-pirates",
        "name": "Arlong Pirates"
      },
      {
        "id": "fish-man",
        "name": "Fish-Man"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "yosaku",
    "name": "Yosaku Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 7% or less: Increase the Treasure Gauge amount when you capture Treasure.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "bounty-hunter",
        "name": "Bounty Hunter"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "hachi",
    "name": "Hachi Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 50% or less: Boost the cooldown reduction speed of Skill 1 by 10%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "arlong-pirates",
        "name": "Arlong Pirates"
      },
      {
        "id": "fish-man",
        "name": "Fish-Man"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "django",
    "name": "Django Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 70% or more: Boost the cooldown reduction speed of Skill 1 by 7%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "black-cat-pirates",
        "name": "Black Cat Pirates"
      },
      {
        "id": "captain",
        "name": "Captain"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "kuro",
    "name": "Kuro Medal",
    "category": "character",
    "uniqueTrait": "When your team has more Treasure secured: Boost the cooldown reduction speed of Skill 1 by 10%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "black-cat-pirates",
        "name": "Black Cat Pirates"
      },
      {
        "id": "captain",
        "name": "Captain"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "gin",
    "name": "Gin Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, Reduce the cooldown time of Skill 1 by 6%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "krieg-s-pirate-armada",
        "name": "Krieg's Pirate Armada"
      },
      {
        "id": "combatant",
        "name": "Combatant"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "don-krieg",
    "name": "Don Krieg Medal",
    "category": "character",
    "uniqueTrait": "When an ally is KO'd (not including you): Reduce the cooldown time of Skill 1 by 3%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "krieg-s-pirate-armada",
        "name": "Krieg's Pirate Armada"
      },
      {
        "id": "captain",
        "name": "Captain"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "poison"
    ]
  },
  {
    "id": "zeff",
    "name": "Zeff Medal",
    "category": "character",
    "uniqueTrait": "When there are 60 seconds or less remaining: CRIT: Boosted by 90% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "cook",
        "name": "Cook"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "yasopp",
    "name": "Yasopp Medal",
    "category": "character",
    "uniqueTrait": "When you capture the Treasure: Reduce the cooldown time of Skill 1 by 8%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "red-haired-pirates",
        "name": "Red-Haired Pirates"
      },
      {
        "id": "sharp-shooter",
        "name": "Sharp Shooter"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "buggy",
    "name": "Buggy Medal",
    "category": "character",
    "uniqueTrait": "When your allies are near the Treasure area where you are at: Boost the cooldown reduction speed of Skill 1 by 10%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "buggy-pirates",
        "name": "Buggy Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "roger-pirates-ex-roger-pirates",
        "name": "Roger Pirates / Ex-Roger Pirates"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "saw",
    "name": "Saw Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, CRIT: Boosted by 120% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "arlong-pirates",
        "name": "Arlong Pirates"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "fish-man",
        "name": "Fish-Man"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "shanks",
    "name": "Shanks Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 70% or more: Boost the cooldown reduction speed of dodge by 13%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "red-haired-pirates",
        "name": "Red-Haired Pirates"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "roger-pirates-ex-roger-pirates",
        "name": "Roger Pirates / Ex-Roger Pirates"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "kaya",
    "name": "Kaya Medal",
    "category": "character",
    "uniqueTrait": "When there are 60 seconds or less remaining: Boost the cooldown reduction speed of Skill 2 by 13%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "hawk-eye",
    "name": "Hawk-Eye Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, Reduce the cooldown time of Skill 1 by 8%.",
    "tags": [
      {
        "id": "east-blue",
        "name": "East Blue"
      },
      {
        "id": "the-seven-warlords-of-the-sea-former-warlords-of-the-sea",
        "name": "The Seven Warlords of the Sea / Former Warlords of the Sea"
      },
      {
        "id": "supreme-grade-sword-wielder",
        "name": "Supreme Grade Sword Wielder"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "smoker",
    "name": "Smoker Medal",
    "category": "character",
    "uniqueTrait": "When Respawned: SPD: Boosted by 6% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "the-grand-line",
        "name": "The Grand Line"
      },
      {
        "id": "navy",
        "name": "Navy"
      },
      {
        "id": "logia",
        "name": "Logia"
      },
      {
        "id": "navy-captain",
        "name": "Navy Captain"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "stun"
    ]
  },
  {
    "id": "slip-slip",
    "name": "Slip-Slip Medal",
    "category": "character",
    "uniqueTrait": "When there are 60 seconds or less remaining: Boost the cooldown reduction speed of Skill 1 by 10%.",
    "tags": [
      {
        "id": "the-grand-line",
        "name": "The Grand Line"
      },
      {
        "id": "the-alvida-pirates",
        "name": "The Alvida Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "wapol",
    "name": "Wapol Medal",
    "category": "character",
    "uniqueTrait": "When your team has more Treasure secured: Boost capture speed by 12%.",
    "tags": [
      {
        "id": "the-grand-line",
        "name": "The Grand Line"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "royalty-former-royalty",
        "name": "Royalty / Former Royalty"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "tashigi",
    "name": "Tashigi Medal",
    "category": "character",
    "uniqueTrait": "When you capture the Treasure: SPD: Boosted by 4% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "the-grand-line",
        "name": "The Grand Line"
      },
      {
        "id": "navy",
        "name": "Navy"
      },
      {
        "id": "master-chief-petty-officer",
        "name": "Master Chief Petty Officer"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "ms-wednesday",
    "name": "Ms. Wednesday Medal",
    "category": "character",
    "uniqueTrait": "When you capture the Treasure: Reduce the cooldown time of Skill 1 by 6%.",
    "tags": [
      {
        "id": "the-grand-line",
        "name": "The Grand Line"
      },
      {
        "id": "baroque-works-former-baroque-works",
        "name": "Baroque Works / Former Baroque Works"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk"
    ],
    "statusReductions": [
      "confuse"
    ]
  },
  {
    "id": "storm",
    "name": "Storm Medal",
    "category": "character",
    "uniqueTrait": "When attacked by an enemy, 30% chance to: Nullify Shock.",
    "tags": [
      {
        "id": "alabasta",
        "name": "Alabasta"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "blood-brothers",
        "name": "Blood Brothers"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "peacock",
    "name": "Peacock Medal",
    "category": "character",
    "uniqueTrait": "When your team has less Treasure secured: Boost the cooldown reduction speed of dodge by 13%.",
    "tags": [
      {
        "id": "alabasta",
        "name": "Alabasta"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "baroque-works-former-baroque-works",
        "name": "Baroque Works / Former Baroque Works"
      },
      {
        "id": "royalty-former-royalty",
        "name": "Royalty / Former Royalty"
      },
      {
        "id": "alabasta-kingdom",
        "name": "Alabasta Kingdom"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk"
    ],
    "statusReductions": [
      "confuse"
    ]
  },
  {
    "id": "mr-zero",
    "name": "Mr. Zero Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, Recover HP by 5%.",
    "tags": [
      {
        "id": "alabasta",
        "name": "Alabasta"
      },
      {
        "id": "the-seven-warlords-of-the-sea-former-warlords-of-the-sea",
        "name": "The Seven Warlords of the Sea/ Former Warlords of the Sea"
      },
      {
        "id": "baroque-works-former-baroque-works",
        "name": "Baroque Works / Former Baroque Works"
      },
      {
        "id": "logia",
        "name": "Logia"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "poison"
    ]
  },
  {
    "id": "pound",
    "name": "Pound Medal",
    "category": "character",
    "uniqueTrait": "When attacking an enemy inflicted with Stun: Increase damage dealt by 3%.",
    "tags": [
      {
        "id": "alabasta",
        "name": "Alabasta"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "sharp-shooter",
        "name": "Sharp Shooter"
      }
    ],
    "nativeTraits": [
      "hp",
      "crit"
    ],
    "statusReductions": [
      "stun"
    ]
  },
  {
    "id": "veau",
    "name": "Veau Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 10% or less: Increase Treasure Gauge recovery amount.",
    "tags": [
      {
        "id": "alabasta",
        "name": "Alabasta"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "cook",
        "name": "Cook"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "climate-baton",
    "name": "Climate Baton Medal",
    "category": "character",
    "uniqueTrait": "When your allies are near the Treasure area where you are at: Boost capture speed by 8%.",
    "tags": [
      {
        "id": "alabasta",
        "name": "Alabasta"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "navigator",
        "name": "Navigator"
      }
    ],
    "nativeTraits": [
      "hp",
      "crit"
    ],
    "statusReductions": [
      "shock"
    ]
  },
  {
    "id": "lion-song",
    "name": "Lion Song Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 50% or less: CRIT: Boosted by 90% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "alabasta",
        "name": "Alabasta"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "combatant",
        "name": "Combatant"
      },
      {
        "id": "great-grade-sword-wielder",
        "name": "Great Grade Sword Wielder"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "ms-all-sunday",
    "name": "Ms. All Sunday Medal",
    "category": "character",
    "uniqueTrait": "When your team has less Treasure secured: Boost capture speed by 8%.",
    "tags": [
      {
        "id": "alabasta",
        "name": "Alabasta"
      },
      {
        "id": "baroque-works-former-baroque-works",
        "name": "Baroque Works / Former Baroque Works"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk"
    ],
    "statusReductions": [
      "tremor"
    ]
  },
  {
    "id": "mr-2",
    "name": "Mr. 2 Medal",
    "category": "character",
    "uniqueTrait": "When in the area around your enemy's Treasure: Increase damage dealt by 5%.",
    "tags": [
      {
        "id": "alabasta",
        "name": "Alabasta"
      },
      {
        "id": "baroque-works-former-baroque-works",
        "name": "Baroque Works / Former Baroque Works"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "officer-agent",
        "name": "Officer Agent"
      },
      {
        "id": "new-kama",
        "name": "New Kama"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "eneru",
    "name": "Eneru Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 70% or more: Boost the cooldown reduction speed of Skill 1 by 13%.",
    "tags": [
      {
        "id": "sky-island-lrll",
        "name": "Sky Island / LRLL"
      },
      {
        "id": "god-s-army",
        "name": "God's Army"
      },
      {
        "id": "logia",
        "name": "Logia"
      },
      {
        "id": "mantra",
        "name": "Mantra"
      }
    ],
    "nativeTraits": [
      "hp",
      "crit"
    ],
    "statusReductions": [
      "shock"
    ]
  },
  {
    "id": "battle-ax",
    "name": "Battle-Ax Medal",
    "category": "character",
    "uniqueTrait": "After KOing an enemy, Reduce the cooldown time of Skill 2 by 8%.",
    "tags": [
      {
        "id": "the-grand-line",
        "name": "The Grand Line"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "blood-brothers",
        "name": "Blood Brothers"
      }
    ],
    "nativeTraits": [
      "hp",
      "crit"
    ],
    "statusReductions": [
      "tremor"
    ]
  },
  {
    "id": "whitebeard",
    "name": "Whitebeard Medal",
    "category": "character",
    "uniqueTrait": "When attacked by an enemy, 30% chance to: Nullify Tremor.",
    "tags": [
      {
        "id": "the-paramount-war-at-marineford",
        "name": "The Paramount War at Marineford"
      },
      {
        "id": "whitebeard-pirates",
        "name": "Whitebeard Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "supreme-grade-sword-wielder",
        "name": "Supreme Grade Sword Wielder"
      },
      {
        "id": "the-four-emperors",
        "name": "The Four Emperors"
      },
      {
        "id": "former-rocks-pirates",
        "name": "Former Rocks Pirates"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "tremor"
    ]
  },
  {
    "id": "aokiji",
    "name": "Aokiji Medal",
    "category": "character",
    "uniqueTrait": "When attacked by an enemy, 30% chance to: Nullify Freeze.",
    "tags": [
      {
        "id": "the-paramount-war-at-marineford",
        "name": "The Paramount War at Marineford"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "freeze"
    ]
  },
  {
    "id": "franky",
    "name": "Franky Medal",
    "category": "character",
    "uniqueTrait": "When an ally is KO'd (not including you): Reduce the cooldown time of Skill 1 by 2%.",
    "tags": [
      {
        "id": "water-7-enies-lobby",
        "name": "Water 7 / Enies Lobby"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "ship-carpenter",
        "name": "Ship Carpenter"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "moria",
    "name": "Moria Medal",
    "category": "character",
    "uniqueTrait": "When an ally is KO'd (not including you): Recover HP by 3%.",
    "tags": [
      {
        "id": "thriller-bark",
        "name": "Thriller Bark"
      },
      {
        "id": "the-seven-warlords-of-the-sea-former-warlords-of-the-sea",
        "name": "The Seven Warlords of the Sea / Former Warlords of the Sea"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "thriller-bark-pirates",
        "name": "Thriller Bark Pirates"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "brook",
    "name": "Brook Medal",
    "category": "character",
    "uniqueTrait": "When attacking an enemy inflicted with Stun: Increase damage dealt by 2%.",
    "tags": [
      {
        "id": "thriller-bark",
        "name": "Thriller Bark"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "musician",
        "name": "Musician"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk"
    ],
    "statusReductions": [
      "stun"
    ]
  },
  {
    "id": "fire-fist",
    "name": "Fire Fist Medal",
    "category": "character",
    "uniqueTrait": "When there are 60 seconds or less remaining: CRIT: Boosted by 120% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "alabasta",
        "name": "Alabasta"
      },
      {
        "id": "whitebeard-pirates",
        "name": "Whitebeard Pirates"
      },
      {
        "id": "logia",
        "name": "Logia"
      },
      {
        "id": "whitebeard-pirates-commander",
        "name": "Whitebeard Pirates Commander"
      },
      {
        "id": "blood-brothers",
        "name": "Blood Brothers"
      }
    ],
    "nativeTraits": [
      "hp",
      "crit"
    ],
    "statusReductions": [
      "aflame"
    ]
  },
  {
    "id": "hancock",
    "name": "Hancock Medal",
    "category": "character",
    "uniqueTrait": "When your team has more Treasure secured: Boost the cooldown reduction speed of Skill 1 by 13%.",
    "tags": [
      {
        "id": "sabaody-archipelago-island-of-women",
        "name": "Sabaody Archipelago / Island of Women"
      },
      {
        "id": "the-seven-warlords-of-the-sea-former-warlords-of-the-sea",
        "name": "The Seven Warlords of the Sea / Former Warlords of the Sea"
      },
      {
        "id": "kuja-pirates",
        "name": "Kuja Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "gorgon-sisters",
        "name": "Gorgon Sisters"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk"
    ],
    "statusReductions": [
      "entrance"
    ]
  },
  {
    "id": "akainu",
    "name": "Akainu Medal",
    "category": "character",
    "uniqueTrait": "When attacked by an enemy, 30% chance to: Nullify Aflame.",
    "tags": [
      {
        "id": "the-paramount-war-at-marineford",
        "name": "The Paramount War at Marineford"
      }
    ],
    "nativeTraits": [
      "hp",
      "crit"
    ],
    "statusReductions": [
      "aflame"
    ]
  },
  {
    "id": "108-pound-phoenix",
    "name": "108 Pound Phoenix Medal",
    "category": "character",
    "uniqueTrait": "When Respawned: SPD: Boosted by 6% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "sky-island-lrll",
        "name": "Sky Island / LRLL"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "combatant",
        "name": "Combatant"
      },
      {
        "id": "great-grade-sword-wielder",
        "name": "Great Grade Sword Wielder"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "arm-point",
    "name": "Arm Point Medal",
    "category": "character",
    "uniqueTrait": "When your allies are not near the Treasure area where you are at: Boost the cooldown reduction speed of dodge by 13%.",
    "tags": [
      {
        "id": "sky-island-lrll",
        "name": "Sky Island / LRLL"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "zoan",
        "name": "Zoan"
      },
      {
        "id": "doctor",
        "name": "Doctor"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "bellamy",
    "name": "Bellamy Medal",
    "category": "character",
    "uniqueTrait": "When in the area around your captured Treasure: Reduce damage received by 3%.",
    "tags": [
      {
        "id": "sky-island-lrll",
        "name": "Sky Island / LRLL"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "law",
    "name": "Law Medal",
    "category": "character",
    "uniqueTrait": "When in the area around your captured Treasure: Boost the cooldown reduction speed of Skill 1 by 13%.",
    "tags": [
      {
        "id": "sabaody-archipelago-island-of-women",
        "name": "Sabaody Archipelago / Island of Women"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "worst-generation",
        "name": "Worst Generation"
      },
      {
        "id": "heart-pirates",
        "name": "Heart Pirates"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "kid",
    "name": "Kid Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 70% or more: Reduce damage received by 5%.",
    "tags": [
      {
        "id": "sabaody-archipelago-island-of-women",
        "name": "Sabaody Archipelago / Island of Women"
      },
      {
        "id": "kid-pirates",
        "name": "Kid Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "worst-generation",
        "name": "Worst Generation"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "elephant-gatling",
    "name": "Elephant Gatling Medal",
    "category": "character",
    "uniqueTrait": "When in the area around your enemy's Treasure: Increase damage dealt by 5%.",
    "tags": [
      {
        "id": "2-years-later",
        "name": "2 Years Later"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "worst-generation",
        "name": "Worst Generation"
      },
      {
        "id": "blood-brothers",
        "name": "Blood Brothers"
      }
    ],
    "nativeTraits": [
      "hp",
      "def",
      "crit"
    ]
  },
  {
    "id": "dragon-quake",
    "name": "Dragon Quake Medal",
    "category": "character",
    "uniqueTrait": "When in the area around your captured Treasure: Boost the cooldown reduction speed of Skill 2 by 13%.",
    "tags": [
      {
        "id": "2-years-later",
        "name": "2 Years Later"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "combatant",
        "name": "Combatant"
      },
      {
        "id": "great-grade-sword-wielder",
        "name": "Great Grade Sword Wielder"
      },
      {
        "id": "worst-generation",
        "name": "Worst Generation"
      }
    ],
    "nativeTraits": [
      "atk",
      "crit"
    ],
    "statusReductions": [
      "stun"
    ]
  },
  {
    "id": "vivi",
    "name": "Vivi Medal",
    "category": "character",
    "uniqueTrait": "When there are 60 seconds or less remaining: Boost the cooldown reduction speed of Skill 2 by 10%.",
    "tags": [
      {
        "id": "reverie",
        "name": "Reverie"
      },
      {
        "id": "baroque-works-former-baroque-works",
        "name": "Baroque Works / Former Baroque Works"
      },
      {
        "id": "royalty-former-royalty",
        "name": "Royalty / Former Royalty"
      },
      {
        "id": "alabasta-kingdom",
        "name": "Alabasta Kingdom"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "thunder",
    "name": "Thunder Medal",
    "category": "character",
    "uniqueTrait": "When you capture the Treasure: SPD: Boosted by 6% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "2-years-later",
        "name": "2 Years Later"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "navigator",
        "name": "Navigator"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "sabo",
    "name": "Sabo Medal",
    "category": "character",
    "uniqueTrait": "When in the area around your captured Treasure: Reduce damage received by 5%.",
    "tags": [
      {
        "id": "dressrosa",
        "name": "Dressrosa"
      },
      {
        "id": "revolutionary-army",
        "name": "Revolutionary Army"
      },
      {
        "id": "chief-of-staff",
        "name": "Chief of Staff"
      },
      {
        "id": "blood-brothers",
        "name": "Blood Brothers"
      }
    ],
    "nativeTraits": [
      "atk",
      "def",
      "crit"
    ]
  },
  {
    "id": "concasser",
    "name": "Concasser Medal",
    "category": "character",
    "uniqueTrait": "When an enemy captures one of your team's Treasure Areas: SPD: Boosted by 6% for 20 second(s). (Cannot Stack)",
    "tags": [
      {
        "id": "2-years-later",
        "name": "2 Years Later"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "cook",
        "name": "Cook"
      }
    ],
    "nativeTraits": [
      "hp",
      "crit"
    ],
    "statusReductions": [
      "aflame"
    ]
  },
  {
    "id": "bonney",
    "name": "Bonney Medal",
    "category": "character",
    "uniqueTrait": "When in the area around your captured Treasure: Reduce damage received by 3%.",
    "tags": [
      {
        "id": "sabaody-archipelago-island-of-women",
        "name": "Sabaody Archipelago / Island of Women"
      },
      {
        "id": "bonney-pirates",
        "name": "Bonney Pirates"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "captain",
        "name": "Captain"
      },
      {
        "id": "worst-generation",
        "name": "Worst Generation"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "green-star",
    "name": "Green Star Medal",
    "category": "character",
    "uniqueTrait": "When you are in your enemy's Treasure Area and the Treasure Gauge is 50% or more: Boost capture speed by 8%.",
    "tags": [
      {
        "id": "2-years-later",
        "name": "2 Years Later"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "sharp-shooter",
        "name": "Sharp Shooter"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk"
    ],
    "statusReductions": [
      "stun"
    ]
  },
  {
    "id": "kizaru",
    "name": "Kizaru Medal",
    "category": "character",
    "uniqueTrait": "When attacked by an enemy, 30% chance to: Nullify Stun.",
    "tags": [
      {
        "id": "the-paramount-war-at-marineford",
        "name": "The Paramount War at Marineford"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk"
    ],
    "statusReductions": [
      "stun"
    ]
  },
  {
    "id": "bed-rest",
    "name": "Bed Rest Medal",
    "category": "character",
    "uniqueTrait": "When your team has less Treasure secured: Reduce damage received by",
    "tags": [
      {
        "id": "2-years-later",
        "name": "2 Years Later"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "zoan",
        "name": "Zoan"
      },
      {
        "id": "doctor",
        "name": "Doctor"
      }
    ],
    "nativeTraits": [
      "hp",
      "atk",
      "def"
    ]
  },
  {
    "id": "mille-fleurs",
    "name": "Mille Fleurs Medal",
    "category": "character",
    "uniqueTrait": "When your HP is 70% or more: Boost the cooldown reduction speed of Skill 1 by 13%.",
    "tags": [
      {
        "id": "2-years-later",
        "name": "2 Years Later"
      },
      {
        "id": "straw-hat-pirates",
        "name": "Straw Hat Pirates"
      },
      {
        "id": "baroque-works-former-baroque-works",
        "name": "Baroque Works / Former Baroque Works"
      },
      {
        "id": "paramecia",
        "name": "Paramecia"
      },
      {
        "id": "archaeologist",
        "name": "Archaeologist"
      }
    ],
    "nativeTraits": [
      "hp",
      "crit"
    ],
    "statusReductions": [
      "tremor"
    ]
  }
] as const satisfies readonly Medal[];
