/* This file is generated by scripts/medal-unique-traits/generate.mjs. */

import type { UniqueTraitCategoryId } from "./unique-trait-categories";

export const uniqueTraitCategoryIdsByMedalId: Readonly<Record<string, readonly UniqueTraitCategoryId[]>> = {
  "future-where-im-the-most-free": [
    "cooldown",
    "skill-2"
  ],
  "tempest-kick-white-thunder": [
    "cooldown",
    "skill-1"
  ],
  "warrior-of-liberation": [
    "damage-increase"
  ],
  "bonneys-daddy": [
    "cooldown",
    "skill-2"
  ],
  "hand-pistol-yellow-lotus": [
    "cooldown",
    "skill-1"
  ],
  "st-marcus-mars": [
    "damage-reduction"
  ],
  "kyros": [
    "damage-reduction"
  ],
  "gungnir": [
    "damage-increase"
  ],
  "stone-stone": [
    "damage-reduction"
  ],
  "the-wings": [
    "cooldown",
    "skill-2"
  ],
  "sew-sew": [
    "cooldown",
    "skill-2"
  ],
  "luffy": [
    "crit-increase",
    "power-up-down"
  ],
  "zoro": [
    "crit-increase",
    "power-up-down"
  ],
  "usopp": [
    "capture-speed"
  ],
  "sanji": [
    "cooldown",
    "skill-1"
  ],
  "nami": [
    "cooldown",
    "skill-1"
  ],
  "chopper": [
    "cooldown",
    "skill-1"
  ],
  "robin": [
    "power-up-down",
    "spd-increase"
  ],
  "butchie": [
    "power-up-down",
    "spd-increase"
  ],
  "koby": [
    "capture-speed"
  ],
  "helmeppo": [
    "power-up-down",
    "spd-increase"
  ],
  "cabaji": [
    "capture-speed"
  ],
  "alvida": [
    "treasure-gauge"
  ],
  "higuma": [
    "power-up-down",
    "spd-increase"
  ],
  "kuroobi": [
    "cooldown",
    "skill-1"
  ],
  "johnny": [
    "capture-speed"
  ],
  "morgan": [
    "crit-increase",
    "power-up-down"
  ],
  "choo": [
    "crit-increase",
    "power-up-down"
  ],
  "yosaku": [
    "treasure-gauge"
  ],
  "hachi": [
    "cooldown",
    "skill-1"
  ],
  "django": [
    "cooldown",
    "skill-1"
  ],
  "kuro": [
    "cooldown",
    "skill-1"
  ],
  "gin": [
    "cooldown",
    "skill-1"
  ],
  "don-krieg": [
    "cooldown",
    "skill-1"
  ],
  "zeff": [
    "crit-increase",
    "power-up-down"
  ],
  "yasopp": [
    "cooldown",
    "skill-1"
  ],
  "buggy": [
    "cooldown",
    "skill-1"
  ],
  "saw": [
    "crit-increase",
    "power-up-down"
  ],
  "shanks": [
    "cooldown"
  ],
  "kaya": [
    "cooldown",
    "skill-2"
  ],
  "hawk-eye": [
    "cooldown",
    "skill-1"
  ],
  "smoker": [
    "power-up-down",
    "spd-increase"
  ],
  "slip-slip": [
    "cooldown",
    "skill-1"
  ],
  "wapol": [
    "capture-speed"
  ],
  "tashigi": [
    "power-up-down",
    "spd-increase"
  ],
  "ms-wednesday": [
    "cooldown",
    "skill-1"
  ],
  "storm": [
    "status-effect-nullification"
  ],
  "peacock": [
    "cooldown"
  ],
  "mr-zero": [
    "hp-recovery"
  ],
  "pound": [
    "damage-increase",
    "status-effect-infliction"
  ],
  "veau": [
    "treasure-gauge"
  ],
  "climate-baton": [
    "capture-speed"
  ],
  "lion-song": [
    "crit-increase",
    "power-up-down"
  ],
  "ms-all-sunday": [
    "capture-speed"
  ],
  "mr-2": [
    "damage-increase"
  ],
  "eneru": [
    "cooldown",
    "skill-1"
  ],
  "battle-ax": [
    "cooldown",
    "skill-2"
  ],
  "whitebeard": [
    "status-effect-nullification"
  ],
  "aokiji": [
    "status-effect-nullification"
  ],
  "franky": [
    "cooldown",
    "skill-1"
  ],
  "moria": [
    "hp-recovery"
  ],
  "brook": [
    "damage-increase",
    "status-effect-infliction"
  ],
  "fire-fist": [
    "crit-increase",
    "power-up-down"
  ],
  "hancock": [
    "cooldown",
    "skill-1"
  ],
  "akainu": [
    "status-effect-nullification"
  ],
  "108-pound-phoenix": [
    "power-up-down",
    "spd-increase"
  ],
  "arm-point": [
    "cooldown"
  ],
  "bellamy": [
    "damage-reduction"
  ],
  "law": [
    "cooldown",
    "skill-1"
  ],
  "kid": [
    "damage-reduction"
  ],
  "elephant-gatling": [
    "damage-increase"
  ],
  "dragon-quake": [
    "cooldown",
    "skill-2"
  ],
  "vivi": [
    "cooldown",
    "skill-2"
  ],
  "thunder": [
    "power-up-down",
    "spd-increase"
  ],
  "sabo": [
    "damage-reduction"
  ],
  "concasser": [
    "power-up-down",
    "spd-increase"
  ],
  "bonney": [
    "damage-reduction"
  ],
  "green-star": [
    "capture-speed",
    "treasure-gauge"
  ],
  "kizaru": [
    "status-effect-nullification"
  ],
  "bed-rest": [
    "damage-reduction"
  ],
  "mille-fleurs": [
    "cooldown",
    "skill-1"
  ],
  "blizzard-slice": [
    "cooldown",
    "skill-1"
  ],
  "radical": [
    "damage-reduction"
  ],
  "bikini-nami": [
    "capture-speed"
  ],
  "bikini-hancock": [
    "damage-increase"
  ],
  "luffy-stampede": [
    "capture-speed"
  ],
  "smoker-stampede": [
    "damage-increase",
    "status-effect-infliction"
  ],
  "sables": [
    "status-effect-infliction"
  ],
  "fire-pillar": [
    "status-effect-nullification"
  ],
  "sabo-stampede": [
    "damage-increase",
    "status-effect-infliction"
  ],
  "billow-white": [
    "capture-speed",
    "treasure-gauge"
  ],
  "king-kong-gun": [
    "damage-increase"
  ],
  "room": [
    "hp-recovery"
  ],
  "hawkins": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "ultra-tiger-hunt": [
    "damage-increase"
  ],
  "katakuri": [
    "damage-increase"
  ],
  "big-mom": [
    "hp-recovery"
  ],
  "nightmare": [
    "damage-increase"
  ],
  "ryuma": [
    "cooldown"
  ],
  "perona": [
    "capture-speed"
  ],
  "bride": [
    "status-effect-infliction"
  ],
  "jinbe": [
    "damage-increase"
  ],
  "boeuf-jarret-jarrer": [
    "cooldown",
    "skill-1"
  ],
  "bege": [
    "cooldown",
    "skill-2"
  ],
  "reiju": [
    "capture-speed"
  ],
  "kuma": [
    "hp-recovery"
  ],
  "snow-creature": [
    "damage-increase"
  ],
  "nipple-light": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "cuerpo-fleurs": [
    "damage-reduction"
  ],
  "kaido": [
    "cooldown",
    "skill-1"
  ],
  "flame-emperor": [
    "status-effect-nullification"
  ],
  "marco": [
    "cooldown",
    "skill-1"
  ],
  "garp": [
    "damage-reduction"
  ],
  "griffon": [
    "cooldown",
    "skill-1"
  ],
  "teech": [
    "cooldown",
    "skill-1"
  ],
  "jet-rocket": [
    "cooldown",
    "skill-1"
  ],
  "bartolomeo": [
    "cooldown",
    "skill-2"
  ],
  "cavendish": [
    "damage-increase"
  ],
  "fujitora": [
    "damage-reduction"
  ],
  "flame-dragon-king": [
    "damage-increase"
  ],
  "lucci": [
    "cooldown",
    "skill-2"
  ],
  "kaku": [
    "power-up-down",
    "spd-increase",
    "skill-1"
  ],
  "firebird-star": [
    "damage-increase"
  ],
  "the-demon-heir": [
    "damage-increase"
  ],
  "mad-dog-of-the-navy": [
    "damage-increase"
  ],
  "cutting-mist": [
    "cooldown",
    "skill-1"
  ],
  "magellan": [
    "damage-reduction"
  ],
  "ivankov": [
    "cooldown",
    "skill-1"
  ],
  "king-cobra": [
    "cooldown",
    "skill-2"
  ],
  "rayleigh": [
    "cooldown",
    "skill-1"
  ],
  "sengoku": [
    "damage-reduction"
  ],
  "urouge": [
    "cooldown",
    "skill-1"
  ],
  "apoo": [
    "cooldown",
    "skill-2"
  ],
  "repel": [
    "damage-increase"
  ],
  "drake": [
    "damage-increase"
  ],
  "killer": [
    "damage-increase"
  ],
  "ninpo-lightning-blast": [
    "cooldown",
    "skill-1"
  ],
  "sumo-slap": [
    "damage-increase"
  ],
  "six-king-pistol": [
    "damage-increase"
  ],
  "mamaragan": [
    "damage-reduction"
  ],
  "rebecca": [
    "cooldown",
    "skill-2"
  ],
  "corazon": [
    "damage-reduction"
  ],
  "ikoku-sovereignty": [
    "capture-speed"
  ],
  "buzz-cut-mochi": [
    "damage-reduction"
  ],
  "chop-chop": [
    "cooldown",
    "skill-2"
  ],
  "caesar": [
    "damage-reduction"
  ],
  "the-master-swordsman": [
    "cooldown",
    "skill-1"
  ],
  "perfume-femur": [
    "damage-increase"
  ],
  "negative-ghost": [
    "cooldown",
    "skill-2"
  ],
  "crescent-cutlass": [
    "capture-speed"
  ],
  "smoker-chambres": [
    "damage-increase"
  ],
  "pheasant-peck": [
    "damage-increase"
  ],
  "kinemon": [
    "damage-reduction"
  ],
  "the-billion-fold-world-trichiliocosm": [
    "damage-increase"
  ],
  "sky-walk": [
    "capture-speed"
  ],
  "cross-fire": [
    "damage-reduction"
  ],
  "chopperemon": [
    "cooldown",
    "skill-1"
  ],
  "kawamatsu": [
    "cooldown",
    "skill-1"
  ],
  "kozuki-oden": [
    "damage-reduction"
  ],
  "kikunojo": [
    "cooldown",
    "skill-1"
  ],
  "roger": [
    "cooldown",
    "skill-1"
  ],
  "napping-kyoshiro": [
    "capture-speed"
  ],
  "ashura-doji": [
    "damage-reduction"
  ],
  "tremor-tremor": [
    "damage-increase"
  ],
  "hero": [
    "damage-reduction"
  ],
  "carrot": [
    "capture-speed"
  ],
  "assistant-fish-man-karate-master": [
    "cooldown"
  ],
  "general-franky": [
    "cooldown",
    "skill-1"
  ],
  "god-usopp": [
    "capture-speed"
  ],
  "gaimon": [
    "damage-reduction"
  ],
  "duke-dogstorm": [
    "damage-increase"
  ],
  "cat-viper": [
    "damage-reduction"
  ],
  "candula": [
    "cooldown",
    "skill-1"
  ],
  "palm": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "raid-luffy": [
    "damage-reduction"
  ],
  "memoir-of-that-summer-day": [
    "capture-speed"
  ],
  "raid-kid": [
    "hp-recovery"
  ],
  "galdino": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "ms-goldenweek": [
    "capture-speed"
  ],
  "pell": [
    "damage-increase"
  ],
  "vivi-karoo": [
    "hp-recovery"
  ],
  "delphinium": [
    "cooldown",
    "skill-1"
  ],
  "ice-burn": [
    "cooldown",
    "skill-1"
  ],
  "sentomaru": [
    "hp-recovery"
  ],
  "koby-paramount-war": [
    "cooldown",
    "skill-2"
  ],
  "fleet-admiral-akainu": [
    "cooldown",
    "skill-2"
  ],
  "baby-5": [
    "cooldown",
    "skill-1"
  ],
  "hard-boiled": [
    "hp-recovery"
  ],
  "hina": [
    "cooldown",
    "skill-2"
  ],
  "scalpel": [
    "capture-speed"
  ],
  "spiky-shadow-lizard": [
    "damage-increase"
  ],
  "fire-fist-pistol-red-hawk": [
    "damage-increase"
  ],
  "raid-law": [
    "damage-increase"
  ],
  "sugar": [
    "hp-recovery"
  ],
  "young-master": [
    "damage-increase"
  ],
  "bamboo-demon": [
    "damage-increase"
  ],
  "monet": [
    "cooldown",
    "skill-1"
  ],
  "sorcery-climate-baton": [
    "damage-reduction"
  ],
  "soul-king": [
    "cooldown",
    "skill-2"
  ],
  "pudding": [
    "cooldown",
    "skill-2"
  ],
  "boss": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "the-dark-king": [
    "hp-recovery"
  ],
  "kanjuro": [
    "hp-recovery"
  ],
  "izo": [
    "damage-increase"
  ],
  "kaidos-son": [
    "cooldown",
    "skill-2"
  ],
  "jack": [
    "cooldown",
    "skill-2"
  ],
  "queen": [
    "cooldown",
    "skill-2"
  ],
  "blast-breath": [
    "damage-increase"
  ],
  "straw-hat": [
    "hp-recovery"
  ],
  "soba-mask": [
    "cooldown",
    "skill-1"
  ],
  "judge": [
    "damage-reduction"
  ],
  "burgess": [
    "cooldown",
    "skill-2"
  ],
  "vista": [
    "capture-speed"
  ],
  "jozu": [
    "damage-reduction"
  ],
  "shiryu": [
    "cooldown",
    "skill-1"
  ],
  "usohachi": [
    "hp-recovery"
  ],
  "franosuke": [
    "damage-increase"
  ],
  "wyper": [
    "damage-increase"
  ],
  "pachycephalosaurus": [
    "damage-reduction"
  ],
  "spinosaurus": [
    "cooldown",
    "skill-2"
  ],
  "phoenix-brand": [
    "capture-speed",
    "treasure-gauge"
  ],
  "perospero": [
    "damage-increase"
  ],
  "hancock-stampede": [
    "power-up-down",
    "spd-increase"
  ],
  "shiki": [
    "capture-speed"
  ],
  "tesoro": [
    "damage-increase"
  ],
  "zephyr": [],
  "luffy-film-red": [
    "crit-increase",
    "power-up-down"
  ],
  "uta": [
    "damage-increase"
  ],
  "beckman-film-red": [
    "hp-recovery"
  ],
  "shanks-film-red": [
    "cooldown",
    "skill-2"
  ],
  "nami-film-red": [
    "cooldown",
    "skill-1"
  ],
  "chopper-film-red": [
    "cooldown",
    "skill-1"
  ],
  "usopp-film-red": [
    "cooldown"
  ],
  "yasopp-film-red": [
    "cooldown",
    "skill-2"
  ],
  "boing-boing": [
    "capture-speed"
  ],
  "ripple-ripple": [
    "hp-recovery"
  ],
  "trebol": [
    "hp-recovery"
  ],
  "shinobu": [
    "capture-speed"
  ],
  "raizo": [
    "power-up-down",
    "spd-increase",
    "skill-2"
  ],
  "hyogoro": [
    "cooldown",
    "skill-1"
  ],
  "x-calibur": [
    "damage-increase"
  ],
  "adio": [
    "damage-increase"
  ],
  "king": [
    "capture-speed"
  ],
  "olin": [
    "damage-reduction",
    "status-effect-infliction"
  ],
  "conqueror-of-three-worlds-ragnaraku": [
    "cooldown",
    "skill-1"
  ],
  "enma": [
    "cooldown",
    "skill-2"
  ],
  "whos-who": [
    "damage-increase"
  ],
  "raid-jinbe": [
    "damage-reduction"
  ],
  "mrs-pudding": [
    "cooldown",
    "skill-2"
  ],
  "brulee": [
    "damage-reduction"
  ],
  "cracker": [
    "damage-increase",
    "skill-2"
  ],
  "leader": [
    "cooldown",
    "status-effect-infliction",
    "skill-2"
  ],
  "oven": [
    "damage-reduction",
    "status-effect-infliction"
  ],
  "hakuba": [
    "capture-speed",
    "treasure-gauge"
  ],
  "chin-jao": [
    "cooldown",
    "skill-2"
  ],
  "kung-fu-jugon": [
    "damage-increase"
  ],
  "elizabello-il": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "ideo": [
    "hp-recovery"
  ],
  "raid-robin": [
    "damage-increase"
  ],
  "raid-brook": [
    "cooldown",
    "status-effect-infliction",
    "skill-1"
  ],
  "namuji-glacier-fang": [
    "cooldown",
    "skill-2"
  ],
  "raid-nami": [
    "damage-reduction"
  ],
  "raid-usopp": [
    "cooldown",
    "skill-1"
  ],
  "vander-decken-ix": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "caribou": [
    "cooldown",
    "skill-2"
  ],
  "shark-pack": [
    "capture-speed",
    "treasure-gauge"
  ],
  "neptune": [
    "cooldown",
    "skill-1"
  ],
  "raid-killer": [
    "cooldown",
    "skill-1"
  ],
  "kid-law": [
    "capture-speed"
  ],
  "shanks-daughter": [
    "damage-increase",
    "status-effect-infliction"
  ],
  "gear-five": [
    "hp-recovery"
  ],
  "raid-sanji": [
    "damage-increase"
  ],
  "heliceratops": [
    "capture-speed"
  ],
  "imperial-flame": [
    "damage-increase"
  ],
  "flying-pan": [
    "hp-recovery"
  ],
  "hack": [
    "cooldown",
    "skill-2"
  ],
  "inazuma": [
    "cooldown",
    "skill-2"
  ],
  "karasu": [
    "capture-speed"
  ],
  "belo-betty": [
    "damage-reduction"
  ],
  "spider-spider": [
    "cooldown",
    "skill-1"
  ],
  "raid-chopper": [
    "cooldown",
    "skill-2"
  ],
  "raid-franky": [
    "cooldown",
    "skill-1"
  ],
  "otama-komachiyo": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "ryokugyu": [
    "capture-speed"
  ],
  "shogun-of-wano": [
    "damage-reduction"
  ],
  "ace-yamato": [
    "damage-reduction"
  ],
  "the-man-who-shook-the-world": [
    "cooldown",
    "skill-1"
  ],
  "paradise-waterfall": [
    "damage-increase"
  ],
  "carrot-whole-cake-island": [
    "damage-increase"
  ],
  "the-man-who-had-everything": [
    "hp-recovery"
  ],
  "the-dark-kings-flash": [
    "damage-reduction"
  ],
  "ganfor": [
    "damage-reduction"
  ],
  "the-great-warrior-kalgara": [
    "damage-increase"
  ],
  "shandias-savior": [
    "hp-recovery"
  ],
  "demaro-black": [
    "damage-reduction"
  ],
  "axe": [
    "cooldown",
    "status-effect-infliction",
    "skill-2"
  ],
  "pacifista": [
    "hp-recovery"
  ],
  "egghead-luffy": [
    "damage-reduction"
  ],
  "s-snake": [
    "damage-reduction"
  ],
  "egghead-zoro": [
    "cooldown",
    "skill-1"
  ],
  "s-hawk": [
    "damage-reduction"
  ],
  "blueno": [
    "damage-reduction"
  ],
  "jabra": [
    "damage-increase"
  ],
  "nose-pistol": [
    "damage-increase"
  ],
  "hand-pistol": [
    "cooldown",
    "skill-2"
  ],
  "vegapunks-spy": [
    "damage-increase"
  ],
  "red-haired-divine-departure": [
    "cooldown",
    "skill-2"
  ],
  "dorry": [
    "damage-increase"
  ],
  "broggy": [
    "damage-reduction"
  ],
  "halloween-uta": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "punk-02": [
    "damage-increase"
  ],
  "s-bear": [
    "hp-recovery"
  ],
  "punk-05": [
    "cooldown",
    "skill-2"
  ],
  "punk-06": [
    "damage-reduction"
  ],
  "s-shark": [
    "cooldown",
    "skill-2"
  ],
  "egghead-sanji": [
    "damage-reduction"
  ],
  "egghead-bonney": [
    "cooldown",
    "skill-1"
  ],
  "lt-commander-helmeppo": [
    "damage-reduction"
  ],
  "galaxy-impact": [
    "damage-increase"
  ],
  "the-future-of-the-navy": [
    "hp-recovery"
  ],
  "former-senior-apprentice": [
    "cooldown",
    "skill-2"
  ],
  "revolutionary-army-female-soldier": [
    "damage-increase"
  ],
  "rook-check": [
    "damage-reduction"
  ],
  "ichiji": [
    "damage-increase"
  ],
  "niji": [
    "cooldown",
    "skill-1"
  ],
  "yonji": [
    "damage-reduction"
  ],
  "invisible-strike": [
    "hp-recovery"
  ],
  "galleon-lariat": [
    "hp-recovery"
  ],
  "st-charlos": [
    "damage-increase"
  ],
  "leo": [
    "damage-reduction"
  ],
  "sai": [
    "hp-recovery"
  ],
  "flail": [
    "cooldown",
    "skill-2"
  ],
  "foxy": [
    "damage-reduction"
  ],
  "arm-e-de-lair-power-shoot": [
    "cooldown",
    "skill-2"
  ],
  "borsalino": [
    "damage-reduction"
  ],
  "aramaki": [
    "cooldown",
    "skill-1"
  ],
  "issho": [
    "hp-recovery"
  ],
  "egghead-nami": [
    "hp-recovery"
  ],
  "egghead-usopp": [
    "damage-reduction"
  ],
  "star-gun": [
    "damage-reduction"
  ],
  "egghead-brook": [
    "damage-increase"
  ],
  "egghead-chopper": [
    "damage-reduction"
  ],
  "egghead-robin": [
    "cooldown",
    "skill-1"
  ],
  "st-jaygarcia-saturn": [
    "damage-reduction"
  ],
  "egghead-franky": [
    "damage-increase",
    "skill-2"
  ],
  "egghead-jinbe": [
    "cooldown",
    "skill-2"
  ],
  "kuma-bonney": [
    "hp-recovery"
  ],
  "genius-scientist": [
    "damage-reduction"
  ],
  "winner-island-bepo": [
    "damage-increase"
  ],
  "winner-island-law": [
    "capture-speed",
    "treasure-gauge"
  ],
  "asl-ace-sabo-luffy": [
    "cooldown"
  ],
  "black-vortex": [
    "damage-reduction"
  ],
  "kilo-kilo": [
    "cooldown",
    "skill-2"
  ],
  "boom-boom": [
    "hp-recovery"
  ],
  "sick-sick": [
    "damage-reduction"
  ],
  "warp-warp": [
    "damage-increase"
  ],
  "st-ethanbaron-v-nusjuro": [
    "cooldown",
    "skill-2"
  ],
  "buddha-sengoku": [
    "hp-recovery"
  ],
  "lapin": [
    "hp-recovery"
  ],
  "dalton": [
    "damage-reduction"
  ],
  "munch-munch": [
    "damage-increase"
  ],
  "luffy-battle-of-monsters-on-onigashima": [
    "power-up-down",
    "spd-increase"
  ],
  "straw-hat-pirates": [],
  "roger-pirates": [
    "damage-increase"
  ],
  "whitebeard-pirates": [
    "damage-increase"
  ],
  "mohji": [
    "hp-increase"
  ],
  "patty": [
    "atk-increase"
  ],
  "luffy-child": [
    "hp-increase"
  ],
  "zoro-child": [
    "crit-increase"
  ],
  "sabo-child": [
    "crit-increase",
    "power-up-down"
  ],
  "ace-child": [
    "hp-recovery"
  ],
  "merry-go": [
    "cooldown",
    "skill-2"
  ],
  "local-sea-monster": [
    "damage-increase"
  ],
  "asl-sabo": [
    "cooldown",
    "skill-2"
  ],
  "asl-luffy": [
    "damage-increase"
  ],
  "mr-5": [
    "cooldown",
    "skill-2"
  ],
  "ms-valentine": [
    "cooldown",
    "skill-2"
  ],
  "chopper-netflix-live-action-series": [
    "damage-increase"
  ],
  "frostbite": [
    "cooldown",
    "skill-2"
  ],
  "falcon": [
    "capture-speed"
  ],
  "jackal": [
    "damage-increase"
  ],
  "mr-1": [
    "cooldown",
    "skill-1"
  ],
  "mr-3": [
    "damage-reduction"
  ],
  "ms-doublefinger": [
    "capture-speed",
    "treasure-gauge"
  ],
  "cobra": [
    "cooldown",
    "skill-1"
  ],
  "chaka": [
    "cooldown",
    "skill-1"
  ],
  "strike-back": [
    "hp-recovery"
  ],
  "rumble-rumble": [
    "status-effect-infliction"
  ],
  "iron-challenge": [
    "cooldown",
    "skill-2"
  ],
  "swamp-challenge": [
    "damage-increase"
  ],
  "kami": [
    "damage-reduction"
  ],
  "kalgara": [
    "cooldown",
    "status-effect-infliction",
    "skill-1"
  ],
  "noland": [
    "hp-recovery",
    "status-effect-infliction"
  ],
  "string-challenge": [
    "hp-recovery"
  ],
  "pierre": [
    "cooldown",
    "skill-1"
  ],
  "cricket": [
    "cooldown",
    "skill-1"
  ],
  "wyper-young": [
    "damage-increase"
  ],
  "porche": [
    "cooldown",
    "skill-2"
  ],
  "hamburg": [
    "cooldown"
  ],
  "chappy": [
    "damage-increase"
  ],
  "usopp-cornerman": [
    "cooldown",
    "skill-2"
  ],
  "wolf": [
    "hp-recovery"
  ],
  "bubble-bubble": [
    "damage-increase"
  ],
  "thousand-sunny": [],
  "fukuro": [
    "capture-speed",
    "treasure-gauge"
  ],
  "kumadori": [
    "cooldown",
    "skill-2"
  ],
  "genie": [
    "hp-recovery"
  ],
  "wild-zombie": [
    "cooldown",
    "skill-1"
  ],
  "mini-merry": [
    "cooldown",
    "skill-2"
  ],
  "murder-machine": [
    "damage-reduction"
  ],
  "mad-monk": [
    "cooldown",
    "skill-2"
  ],
  "red-flag": [
    "cooldown",
    "skill-2"
  ],
  "roar-of-the-sea": [
    "capture-speed"
  ],
  "gang": [
    "damage-reduction"
  ],
  "magician": [
    "cooldown",
    "skill-1"
  ],
  "sandersonia": [
    "cooldown",
    "skill-2"
  ],
  "marigold": [
    "cooldown",
    "skill-1"
  ],
  "light-human": [
    "cooldown",
    "skill-2"
  ],
  "st-roswald": [
    "cooldown",
    "skill-2"
  ],
  "gas-gas": [
    "cooldown",
    "skill-1"
  ],
  "warrior": [
    "cooldown",
    "skill-1"
  ],
  "happosui-army": [
    "cooldown",
    "skill-2"
  ],
  "former-cp9-director": [
    "cooldown",
    "skill-2"
  ],
  "stick-stick": [
    "cooldown",
    "skill-2"
  ],
  "hobby-hobby": [
    "damage-reduction"
  ],
  "lucy-luffy": [
    "hp-recovery"
  ],
  "robiland": [
    "cooldown",
    "skill-2"
  ],
  "pica": [
    "damage-increase"
  ],
  "buffalo": [
    "damage-reduction"
  ],
  "diamante": [
    "cooldown",
    "skill-2"
  ],
  "dellinger": [
    "crit-increase",
    "power-up-down"
  ],
  "savior": [
    "damage-increase"
  ],
  "pop-pop": [
    "cooldown",
    "skill-1"
  ],
  "art-art": [
    "damage-reduction"
  ],
  "glare-glare": [
    "damage-reduction"
  ],
  "ton-ton": [
    "damage-increase"
  ],
  "barrier-barrier": [
    "cooldown",
    "skill-2"
  ],
  "hajrudin": [
    "damage-reduction"
  ],
  "hajrudin-straw-hat-fleet": [
    "damage-increase"
  ],
  "bartolomeo-straw-hat-fleet": [
    "cooldown",
    "skill-2"
  ],
  "joker": [
    "cooldown",
    "skill-2"
  ],
  "all-seeing-eye": [
    "damage-increase",
    "skill-2"
  ],
  "half-n-half": [
    "cooldown",
    "skill-2"
  ],
  "mermaid-princess": [
    "cooldown",
    "skill-2"
  ],
  "attendant-of-dressrosa": [
    "cooldown",
    "skill-1"
  ],
  "conney": [
    "crit-increase",
    "power-up-down"
  ],
  "koala-reverie": [
    "cooldown",
    "skill-2"
  ],
  "push-push": [
    "cooldown",
    "skill-2"
  ],
  "horm-horm": [
    "cooldown",
    "skill-1"
  ],
  "inventor": [
    "cooldown",
    "skill-1"
  ],
  "princess-of-alabasta": [
    "cooldown",
    "skill-1"
  ],
  "captain-koby": [
    "damage-increase"
  ],
  "wring-wring": [
    "cooldown",
    "skill-2"
  ],
  "bis-bis": [
    "crit-increase",
    "power-up-down"
  ],
  "memo-memo": [
    "cooldown",
    "skill-1"
  ],
  "chiffon": [
    "cooldown",
    "skill-2"
  ],
  "zeus": [
    "status-effect-nullification"
  ],
  "prometheus": [
    "status-effect-nullification"
  ],
  "napoleon": [
    "damage-increase"
  ],
  "queen-of-the-pleasure-district": [
    "cooldown",
    "skill-1"
  ],
  "mirror-mirror": [
    "cooldown",
    "skill-1"
  ],
  "truly-favored-sister": [
    "cooldown",
    "skill-2"
  ],
  "pekoms": [
    "cooldown"
  ],
  "pedro": [],
  "shishilian": [
    "damage-increase",
    "status-effect-infliction"
  ],
  "wanda": [
    "status-effect-infliction",
    "power-up-down",
    "spd-increase"
  ],
  "puff-puff": [
    "damage-increase"
  ],
  "heat-heat": [
    "cooldown",
    "skill-1"
  ],
  "chopper-whole-cake-island": [
    "capture-speed"
  ],
  "pedro-whole-cake-island": [
    "cooldown",
    "status-effect-infliction",
    "skill-1"
  ],
  "aladdin": [
    "damage-increase"
  ],
  "praline": [
    "damage-reduction"
  ],
  "lucky-fellow": [
    "cooldown",
    "skill-1"
  ],
  "gourmet-knight": [
    "cooldown",
    "skill-2"
  ],
  "mochi-mochi": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "montdor": [
    "cooldown",
    "treasure-gauge",
    "skill-1",
    "skill-2"
  ],
  "carrot-sulong": [
    "cooldown",
    "status-effect-infliction",
    "skill-1"
  ],
  "mystoms": [
    "cooldown",
    "status-effect-nullification",
    "skill-1"
  ],
  "milky": [
    "hp-recovery",
    "status-effect-infliction"
  ],
  "tristan": [
    "cooldown",
    "skill-1"
  ],
  "foxfire": [
    "cooldown",
    "skill-2"
  ],
  "evening-shower": [
    "cooldown"
  ],
  "plague": [
    "cooldown",
    "skill-2"
  ],
  "drought": [
    "damage-increase"
  ],
  "straw-straw": [
    "damage-increase"
  ],
  "starving-skeleton": [
    "capture-speed"
  ],
  "geisha": [
    "damage-reduction"
  ],
  "carpenter": [
    "crit-increase",
    "power-up-down"
  ],
  "toad-oil-salesman": [
    "cooldown",
    "skill-2"
  ],
  "momonosuke": [
    "capture-speed",
    "treasure-gauge"
  ],
  "hiyori": [
    "cooldown",
    "skill-2"
  ],
  "the-strongest-creature": [
    "damage-increase"
  ],
  "raizo-of-the-mist": [
    "cooldown",
    "skill-1"
  ],
  "veteran-kunoichi": [
    "cooldown",
    "skill-2"
  ],
  "kids-partner": [
    "damage-reduction"
  ],
  "bepo": [
    "cooldown",
    "skill-2"
  ],
  "soba-cart-cook": [
    "hp-recovery"
  ],
  "ronin": [
    "cooldown",
    "skill-1"
  ],
  "izo-child": [
    "cooldown",
    "skill-1"
  ],
  "kikunojo-child": [
    "hp-recovery"
  ],
  "ace-land-of-wano": [
    "cooldown",
    "skill-1"
  ],
  "otama": [
    "hp-recovery"
  ],
  "ulti": [],
  "page-one": [
    "cooldown",
    "treasure-gauge",
    "skill-1"
  ],
  "wildfire": [
    "cooldown",
    "skill-1"
  ],
  "black-maria": [
    "cooldown",
    "skill-1"
  ],
  "saber-toothed-tiger": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "triceratops": [
    "cooldown",
    "skill-1"
  ],
  "daifuku-land-of-wano": [
    "cooldown",
    "skill-1"
  ],
  "flampe-land-of-wano": [
    "cooldown",
    "skill-2"
  ],
  "kinemon-the-akazaya-nine": [
    "hp-recovery"
  ],
  "denjiro-the-akazaya-nine": [
    "cooldown",
    "skill-1"
  ],
  "eleph-eleph": [
    "hp-recovery"
  ],
  "sasaki": [
    "cooldown",
    "skill-1"
  ],
  "smoothie-pirate-alliance": [
    "hp-recovery",
    "status-effect-infliction"
  ],
  "perospero-pirate-alliance": [
    "damage-increase",
    "damage-reduction",
    "treasure-gauge"
  ],
  "red-roc": [
    "damage-increase"
  ],
  "rotisserie-strike": [
    "cooldown",
    "skill-1"
  ],
  "zoro-bandages": [
    "cooldown",
    "skill-2"
  ],
  "baby-geezer-chopper": [
    "capture-speed",
    "treasure-gauge"
  ],
  "ace-izayoizuki": [
    "cooldown",
    "skill-1"
  ],
  "momonosuke-dragon": [
    "capture-speed"
  ],
  "lightning-blast": [
    "hp-recovery",
    "status-effect-infliction"
  ],
  "komachiyo": [
    "cooldown",
    "skill-2"
  ],
  "hera": [
    "cooldown",
    "damage-reduction",
    "treasure-gauge",
    "skill-1"
  ],
  "prometheus-land-of-wano": [
    "hp-recovery",
    "status-effect-infliction"
  ],
  "kong-gun": [
    "hp-recovery"
  ],
  "purgatory-onigiri": [
    "cooldown",
    "skill-2"
  ],
  "three-captains-luffy": [
    "damage-reduction"
  ],
  "three-captains-kid": [
    "hp-recovery"
  ],
  "three-captains-law": [],
  "kaido-human-monster-form": [
    "cooldown",
    "skill-1"
  ],
  "jack-human-monster-form": [
    "capture-speed"
  ],
  "ulti-human-monster-form": [
    "cooldown",
    "skill-2"
  ],
  "page-one-human-monster-form": [
    "damage-increase"
  ],
  "jinbe-onigashima-infiltration": [
    "damage-increase"
  ],
  "robin-onigashima-infiltration": [
    "cooldown",
    "skill-1"
  ],
  "speed": [
    "cooldown",
    "skill-1"
  ],
  "daifugo": [
    "cooldown",
    "skill-1"
  ],
  "yamato-post-onigashima": [
    "damage-increase"
  ],
  "princess-hiyori": [
    "capture-speed"
  ],
  "luffy-post-onigashima": [
    "damage-increase"
  ],
  "otama-post-onigashima": [
    "cooldown",
    "skill-2"
  ],
  "redtaro": [
    "cooldown",
    "skill-2"
  ],
  "buggyjiro": [
    "cooldown",
    "skill-2"
  ],
  "zoro-feast": [
    "damage-reduction"
  ],
  "king-bandaged": [
    "hp-recovery"
  ],
  "pteranodon": [
    "capture-speed"
  ],
  "brachiosaurus": [
    "capture-speed"
  ],
  "the-man-who-will-be-king-of-the-pirates": [
    "damage-reduction"
  ],
  "azure-dragon": [
    "damage-reduction"
  ],
  "demonio-fleur": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "chopper-monster": [
    "damage-increase"
  ],
  "bonney-kid": [
    "cooldown",
    "skill-2"
  ],
  "lilith": [],
  "dr-vegapunk": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "luffy-future-outfit": [
    "cooldown",
    "skill-2"
  ],
  "zoro-future-outfit": [
    "damage-increase"
  ],
  "stussy-cpo": [
    "cooldown",
    "skill-1"
  ],
  "hattori-cpo": [
    "damage-increase"
  ],
  "shaka": [
    "cooldown",
    "skill-1"
  ],
  "edison": [
    "cooldown",
    "skill-2"
  ],
  "oimo": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "kashii": [
    "hp-recovery"
  ],
  "vegaforce-01": [
    "cooldown",
    "skill-1"
  ],
  "pythagoras": [
    "cooldown",
    "skill-2"
  ],
  "luffy-lucci": [
    "cooldown",
    "skill-1"
  ],
  "bonneys-father": [],
  "brook-future-outfit": [
    "cooldown",
    "skill-2"
  ],
  "chopper-future-outfit": [
    "cooldown",
    "skill-2"
  ],
  "robin-future-outfit": [
    "cooldown",
    "skill-1"
  ],
  "nami-future-outfit": [
    "damage-increase"
  ],
  "peacock-fullalead": [
    "cooldown",
    "skill-2"
  ],
  "tashigi-fullalead": [
    "cooldown",
    "skill-1"
  ],
  "prince-grus-fullalead": [
    "cooldown",
    "skill-1"
  ],
  "hibari-fullalead": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "garp-fullalead": [
    "damage-increase"
  ],
  "helmeppo-fullalead": [
    "cooldown",
    "skill-2"
  ],
  "captain-of-the-eastern-forces": [
    "cooldown",
    "skill-1"
  ],
  "vice-captain-of-the-eastern-forces": [
    "damage-increase"
  ],
  "free-form": [
    "cooldown",
    "skill-1"
  ],
  "kumas-daughter": [
    "damage-reduction"
  ],
  "doll": [],
  "bluegrass": [
    "damage-increase"
  ],
  "edison-bandaged": [
    "cooldown",
    "skill-2"
  ],
  "atlas-order": [
    "damage-reduction"
  ],
  "a-hundred-times-stronger": [
    "cooldown",
    "skill-1"
  ],
  "sanji-future-outfit": [
    "cooldown",
    "skill-2"
  ],
  "usopp-future-outfit": [
    "cooldown",
    "skill-1"
  ],
  "franky-future-outfit": [
    "damage-reduction"
  ],
  "zoro-kaku": [
    "damage-increase"
  ],
  "jinbe-future-outfit": [
    "damage-increase"
  ],
  "warrior-god-of-justice": [
    "hp-recovery"
  ],
  "warrior-god-of-agriculture": [
    "cooldown",
    "skill-2"
  ],
  "ginny-child": [
    "cooldown",
    "skill-2"
  ],
  "sentomaru-child": [
    "hp-recovery"
  ],
  "winner-takes-all": [
    "cooldown",
    "skill-2"
  ],
  "sulong": [
    "cooldown",
    "skill-2"
  ],
  "the-four-emperors-blackbeard": [
    "damage-increase"
  ],
  "the-four-emperors-red-hair": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "the-four-emperors-straw-hat": [
    "cooldown",
    "skill-2"
  ],
  "the-four-emperors-genius-jester": [
    "damage-increase",
    "skill-2"
  ],
  "avalo-pizarro": [
    "damage-increase"
  ],
  "vasco-shot": [
    "cooldown",
    "skill-2"
  ],
  "godhead-of-environment": [
    "damage-increase"
  ],
  "godhead-of-science-defense": [
    "damage-increase"
  ],
  "lucci-mask": [
    "damage-reduction"
  ],
  "kaku-mask": [
    "cooldown",
    "skill-1"
  ],
  "gyuki": [
    "hp-recovery"
  ],
  "godhead-of-finance": [
    "damage-reduction"
  ],
  "s-snake-blushing": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "s-hawk-dice-dice": [
    "cooldown",
    "skill-1",
    "skill-2"
  ],
  "luffy-film-strong-world": [
    "cooldown",
    "skill-1"
  ],
  "nami-film-strong-world": [
    "cooldown",
    "skill-1"
  ],
  "sanji-film-gold": [
    "cooldown",
    "skill-1"
  ],
  "usopp-film-gold": [
    "cooldown",
    "skill-1"
  ],
  "zoro-film-z": [
    "cooldown",
    "skill-1"
  ],
  "chopper-film-z": [
    "cooldown",
    "skill-1"
  ],
  "admiral-zephyr": [
    "hp-recovery"
  ],
  "kuzan-film-z": [
    "damage-reduction"
  ],
  "bullet": [
    "status-effect-nullification"
  ],
  "festa": [
    "crit-increase",
    "power-up-down"
  ],
  "tashigi-stampede": [
    "damage-reduction"
  ],
  "lucci-stampede": [
    "hp-recovery"
  ],
  "ann": [
    "damage-increase"
  ],
  "usopp-stampede": [
    "capture-speed"
  ],
  "law-stampede": [
    "cooldown",
    "status-effect-infliction",
    "skill-2"
  ],
  "clank-clank": [
    "cooldown",
    "skill-1"
  ],
  "jinbe-film-red": [
    "cooldown",
    "skill-1"
  ],
  "robin-film-red": [
    "cooldown",
    "skill-2"
  ],
  "lucky-roux-film-red": [
    "hp-recovery"
  ],
  "limejuice-film-red": [
    "damage-reduction"
  ],
  "franky-film-red": [
    "damage-reduction"
  ],
  "brook-film-red": [
    "cooldown",
    "skill-2"
  ],
  "sunny-kun-film-red": [
    "damage-increase"
  ],
  "rockstar-film-red": [
    "cooldown",
    "skill-2"
  ],
  "utas-father": [],
  "gordon": [
    "cooldown",
    "skill-1"
  ],
  "lim": [
    "cooldown",
    "skill-2"
  ],
  "dry-penguin": [
    "damage-increase"
  ],
  "marco-young": [
    "cooldown",
    "skill-1"
  ],
  "jozu-young": [
    "cooldown",
    "damage-reduction",
    "treasure-gauge",
    "skill-2"
  ],
  "oden-roger-pirates": [
    "cooldown",
    "skill-2"
  ],
  "oden-2nd-division-commander": [
    "cooldown",
    "skill-2"
  ],
  "vista-land-of-wano-memoir": [
    "cooldown",
    "skill-1"
  ],
  "marco-land-of-wano-memoir": [
    "cooldown",
    "skill-2"
  ],
  "fisher-tiger": [
    "damage-reduction"
  ],
  "arlong-sun-pirates": [
    "damage-reduction"
  ],
  "reiju-child": [
    "capture-speed"
  ],
  "sanji-child": [
    "damage-reduction"
  ],
  "cat-burglar": [
    "capture-speed",
    "treasure-gauge"
  ],
  "pirate-hunter": [
    "cooldown",
    "skill-1"
  ],
  "admiral-sengoku": [
    "cooldown",
    "skill-1"
  ],
  "vice-admiral-tsuru": [
    "damage-increase"
  ],
  "loan-shark": [
    "damage-increase"
  ],
  "iron-mace": [
    "cooldown",
    "skill-1"
  ],
  "miracle-worker": [
    "damage-reduction"
  ],
  "koala": [
    "damage-increase"
  ],
  "red-hair": [
    "cooldown",
    "skill-1"
  ],
  "genius-jester": [
    "cooldown",
    "skill-2"
  ],
  "shanks-child": [
    "damage-reduction"
  ],
  "buggy-child": [
    "crit-increase",
    "power-up-down"
  ],
  "crocus-roger-pirata": [
    "cooldown",
    "skill-1"
  ],
  "the-pirate-kings-right-arm": [
    "hp-recovery"
  ],
  "roger-captain": [
    "damage-increase"
  ],
  "rayleigh-first-mate": [
    "cooldown"
  ]
};

export const uniqueTraitCategoryNeedsReview = [
  {
    "id": "zephyr",
    "uniqueTrait": "When in the area around your captured Treasure: Boost the by 13%.",
    "reason": "The effect name is missing after the activation condition."
  },
  {
    "id": "thousand-sunny",
    "uniqueTrait": "When attacking an enemy with a Normal Attack, 30% chance to: by 3%.",
    "reason": "The effect name is missing after the activation condition."
  },
  {
    "id": "pedro",
    "uniqueTrait": "When you capture the Treasure: by 5%.",
    "reason": "The effect name is missing after the activation condition."
  },
  {
    "id": "ulti",
    "uniqueTrait": "When you Knockback an enemy: by 5%.",
    "reason": "The effect name is missing after the activation condition."
  },
  {
    "id": "three-captains-law",
    "uniqueTrait": "When you capture the Treasure: by 8%.",
    "reason": "The effect name is missing after the activation condition."
  },
  {
    "id": "lilith",
    "uniqueTrait": "When you capture the Treasure: by 6%.",
    "reason": "The effect name is missing after the activation condition."
  },
  {
    "id": "bonneys-father",
    "uniqueTrait": "When you Knockback an enemy: by 3%.",
    "reason": "The effect name is missing after the activation condition."
  },
  {
    "id": "doll",
    "uniqueTrait": "When you Knockback an enemy: by 5%.",
    "reason": "The effect name is missing after the activation condition."
  },
  {
    "id": "utas-father",
    "uniqueTrait": "When you Knockback an enemy: tale by 5%.",
    "reason": "The effect name is missing after the activation condition."
  }
] as const;
