/* This file is generated by scripts/scout-importer/import.mjs. */

import type {
    ScoutBanner,
    ScoutPickup,
} from "./type";

const pickups = [
    {
        characterId: "the-wings-zoro-sanji",
        rate: 0.2,
    },
] satisfies readonly ScoutPickup[];

const totalPickupRate = pickups.reduce(
    (total, pickup) => total + pickup.rate,
    0,
);

export const scout260MillionDownloadsCelebrationExtremeBountyFestival2: ScoutBanner = {
    id: "260-million-downloads-celebration-extreme-bounty-festival-2",
    name: "Ex Zoro & Sanji Revival",
    bannerImg: "/scouts/260-million-downloads-celebration-extreme-bounty-festival-2.webp",
    startAt: "2026-09-04T14:00:00+09:00",
    endAt: "2026-09-18T13:59:59+09:00",
    pullOptions: {
        single: { pullCount: 1, diamondCost: 5 },
        multi: { pullCount: 11, diamondCost: 50 },
    },
    pickups,
    featuredCharacterId: "the-wings-zoro-sanji",
    rates: {
        pickup: totalPickupRate,
        bf: 2.88,
        "star-4": 3.92,
        "star-3": 35,
        "star-2": 58,
    },
};
