/* This file is generated by scripts/scout-importer/import.mjs. */

import type {
    ScoutBanner,
    ScoutPickup,
} from "./type";

const pickups = [
    {
        characterId: "battle-of-monsters-on-onigashima-kaido",
        rate: 0.2,
    },
    {
        characterId: "legendary-gladiator-kyros",
        rate: 0.5,
    },
    {
        characterId: "sakura-kingdom-king-dalton",
        rate: 0.5,
    },
    {
        characterId: "clear-clear-fruit-shiryu",
        rate: 0.5,
    },
] satisfies readonly ScoutPickup[];

const totalPickupRate = pickups.reduce(
    (total, pickup) => total + pickup.rate,
    0,
);

export const scout260MillionDownloadsCelebrationExtremeBountyFestival: ScoutBanner = {
    id: "260-million-downloads-celebration-extreme-bounty-festival",
    name: "Ex Hybrid Kaido Revival",
    bannerImg: "/scouts/260-million-downloads-celebration-extreme-bounty-festival.webp",
    startAt: "2026-09-04T14:00:00+09:00",
    endAt: "2026-09-09T13:59:59+09:00",
    pullOptions: {
        single: { pullCount: 1, diamondCost: 5 },
        multi: { pullCount: 11, diamondCost: 50 },
    },
    pickups,
    featuredCharacterId: "battle-of-monsters-on-onigashima-kaido",
    rates: {
        pickup: totalPickupRate,
        bf: 1.34,
        "star-4": 3.96,
        "star-3": 35,
        "star-2": 58,
    },
};
