/* This file is generated by scripts/scout-importer/import.mjs. */

import type {
    ScoutBanner,
    ScoutPickup,
} from "./type";

const pickups = [
    {
        characterId: "giant-warrior-hajrudin",
        rate: 0.5,
    },
    {
        characterId: "don-quixote-pirates-supreme-officer-pica",
        rate: 0.5,
    },
    {
        characterId: "asl-ace-sabo-luffy",
        rate: 0.5,
    },
    {
        characterId: "egghead-jinbe",
        rate: 0.5,
    },
    {
        characterId: "egghead-tony-tony-chopper",
        rate: 0.5,
    },
    {
        characterId: "germa-66-vinsmoke-ichiji",
        rate: 0.5,
    },
] satisfies readonly ScoutPickup[];

const totalPickupRate = pickups.reduce(
    (total, pickup) => total + pickup.rate,
    0,
);

export const scoutGiantWarriorHajrudin20260928: ScoutBanner = {
    id: "giant-warrior-hajrudin-20260928",
    name: "BF Summer 2026",
    bannerImg: "/scouts/giant-warrior-hajrudin-20260928.webp",
    startAt: "2026-09-05T14:00:00+09:00",
    endAt: "2026-09-28T13:59:59+09:00",
    pullOptions: {
        single: { pullCount: 1, diamondCost: 5 },
        multi: { pullCount: 11, diamondCost: 50 },
    },
    pickups,
    featuredCharacterId: "giant-warrior-hajrudin",
    rates: {
        pickup: totalPickupRate,
        bf: 1.03,
        "star-4": 2.97,
        "star-3": 35,
        "star-2": 58,
    },
};
