/* This file is generated by scripts/scout-importer/import.mjs. */

import type {
    ScoutBanner,
    ScoutPickup,
} from "./type";

const pickups = [
    {
        characterId: "kaido-s-son-yamato",
        rate: 0.2,
    },
] satisfies readonly ScoutPickup[];

const totalPickupRate = pickups.reduce(
    (total, pickup) => total + pickup.rate,
    0,
);

export const scoutKaidoSSonYamato20260924: ScoutBanner = {
    id: "kaido-s-son-yamato-20260924",
    name: "260 Million Downloads Celebration EX#5",
    bannerImg: "/scouts/kaido-s-son-yamato-20260924.webp",
    startAt: "2026-09-17T14:00:00+09:00",
    endAt: "2026-09-24T13:59:59+09:00",
    pullOptions: {
        single: { pullCount: 1, diamondCost: 5 },
        multi: { pullCount: 11, diamondCost: 50 },
    },
    pickups,
    featuredCharacterId: "kaido-s-son-yamato",
    rates: {
        pickup: totalPickupRate,
        bf: 2.9,
        "star-4": 3.9,
        "star-3": 35,
        "star-2": 58,
    },
};
