/* This file is generated by scripts/scout-importer/import.mjs. */

import type {
    ScoutBanner,
    ScoutPickup,
} from "./type";

const pickups = [
    {
        characterId: "paramount-war-sengoku",
        rate: 0.2222222,
    },
    {
        characterId: "groves-of-wrath-ryokugyu",
        rate: 0.2222222,
    },
    {
        characterId: "blind-swordsman-fujitora",
        rate: 0.2222222,
    },
    {
        characterId: "navy-hq-admiral-ryokugyu",
        rate: 0.2222222,
    },
    {
        characterId: "navy-hq-fleet-admiral-sengoku",
        rate: 0.2222222,
    },
    {
        characterId: "navy-hq-admiral-fujitora",
        rate: 0.2222222,
    },
    {
        characterId: "navy-hq-admiral-kizaru",
        rate: 0.2222222,
    },
    {
        characterId: "navy-hq-admiral-aokiji",
        rate: 0.2222222,
    },
    {
        characterId: "navy-hq-admiral-akainu",
        rate: 0.2222222,
    },
    {
        characterId: "former-navy-admiral-kuzan",
        rate: 3,
    },
] satisfies readonly ScoutPickup[];

export const scoutNavyHqFleetAdmiralSengoku20260924: ScoutBanner = {
    id: "navy-hq-fleet-admiral-sengoku-20260924",
    name: "Navy Admiral / Former Navy Admiral Featured Scout",
    bannerImg: "/scouts/navy-hq-fleet-admiral-sengoku-20260924.webp",
    startAt: "2026-09-23T14:00:00+09:00",
    endAt: "2026-09-24T13:59:59+09:00",
    pullOptions: {
        single: { pullCount: 1, diamondCost: 5 },
        multi: { pullCount: 11, diamondCost: 50 },
    },
    pickups,
    featuredCharacterId: "navy-hq-fleet-admiral-sengoku",
    rates: {
        pickup: 5,
        bf: 0,
        "star-4": 0,
        "star-3": 35,
        "star-2": 60,
    },
};
