/* This file is generated by scripts/scout-importer/import.mjs. */

import type {
    ScoutBanner,
    ScoutPickup,
} from "./type";

const pickups = [
    {
        characterId: "navy-hq-sword-prince-grus",
        rate: 1,
    },
    {
        characterId: "navy-hq-sword-koby",
        rate: 1,
    },
] satisfies readonly ScoutPickup[];

const totalPickupRate = pickups.reduce(
    (total, pickup) => total + pickup.rate,
    0,
);

export const scoutNavyHqSwordKoby20261013: ScoutBanner = {
    id: "navy-hq-sword-koby-20261013",
    name: "BF \"Sword\"",
    bannerImg: "/scouts/navy-hq-sword-koby-20261013.webp",
    startAt: "2026-09-17T14:00:00+09:00",
    endAt: "2026-10-13T13:59:59+09:00",
    pullOptions: {
        single: { pullCount: 1, diamondCost: 5 },
        multi: { pullCount: 11, diamondCost: 50 },
    },
    pickups,
    featuredCharacterId: "navy-hq-sword-koby",
    rates: {
        pickup: totalPickupRate,
        bf: 1.02,
        "star-4": 3.98,
        "star-3": 35,
        "star-2": 58,
    },
};
