/* This file is generated by scripts/scout-importer/import.mjs. */

import type {
    ScoutBanner,
    ScoutPickup,
} from "./type";

const pickups = [
    {
        characterId: "navy-hq-sword-hibari",
        rate: 1,
    },
] satisfies readonly ScoutPickup[];

const totalPickupRate = pickups.reduce(
    (total, pickup) => total + pickup.rate,
    0,
);

export const scoutNavyHqSwordHibari20261001: ScoutBanner = {
    id: "navy-hq-sword-hibari-20261001",
    name: "Sword Hibari",
    bannerImg: "/scouts/navy-hq-sword-hibari-20261001.webp",
    startAt: "2026-09-17T14:00:00+09:00",
    endAt: "2026-10-01T13:59:59+09:00",
    pullOptions: {
        single: { pullCount: 1, diamondCost: 5 },
        multi: { pullCount: 11, diamondCost: 50 },
    },
    pickups,
    featuredCharacterId: "navy-hq-sword-hibari",
    rates: {
        pickup: totalPickupRate,
        bf: 0,
        "star-4": 4,
        "star-3": 35,
        "star-2": 60,
    },
};
