/* This file is generated by scripts/scout-importer/import.mjs. */

import type {
    ScoutBanner,
    ScoutPickup,
} from "./type";

const pickups = [
    {
        characterId: "raid-on-onigashima-sanji",
        rate: 0.5,
    },
    {
        characterId: "animal-kingdom-pirates-tobi-roppo-who-s-who",
        rate: 0.5,
    },
    {
        characterId: "enies-lobby-nico-robin",
        rate: 0.5,
    },
    {
        characterId: "roger-s-rival-edward-newgate",
        rate: 0.5,
    },
    {
        characterId: "the-billion-fold-world-trichiliocosm-roronoa-zoro",
        rate: 0.5,
    },
    {
        characterId: "luffy-law-pirates-aliance-monkey-d-luffy",
        rate: 0.5,
    },
    {
        characterId: "kuja-pirates-captain-boa-hancock",
        rate: 0.5,
    },
    {
        characterId: "navy-hq-fleet-admiral-sengoku",
        rate: 0.5,
    },
    {
        characterId: "land-of-wano-luffytaro",
        rate: 0.5,
    },
    {
        characterId: "peacock-slasher-nefeltari-vivi",
        rate: 0.5,
    },
] satisfies readonly ScoutPickup[];

const totalPickupRate = pickups.reduce(
    (total, pickup) => total + pickup.rate,
    0,
);

export const scoutRaidOnOnigashimaSanji20260914: ScoutBanner = {
    id: "raid-on-onigashima-sanji-20260914",
    name: "260 Million Downloads Celebration",
    bannerImg: "/scouts/raid-on-onigashima-sanji-20260914.webp",
    startAt: "2026-09-07T14:00:00+09:00",
    endAt: "2026-09-14T13:59:59+09:00",
    pullOptions: {
        single: { pullCount: 1, diamondCost: 5 },
        multi: { pullCount: 11, diamondCost: 50 },
    },
    pickups,
    featuredCharacterId: "raid-on-onigashima-sanji",
    rates: {
        pickup: totalPickupRate,
        bf: 0,
        "star-4": 0,
        "star-3": 35,
        "star-2": 60,
    },
};
