/* This file is generated by scripts/scout-importer/import.mjs. */

import type {
    ScoutBanner,
    ScoutPickup,
} from "./type";

const pickups = [
    {
        characterId: "the-four-emperors-marshall-d-teach",
        rate: 0.2,
    },
] satisfies readonly ScoutPickup[];

const totalPickupRate = pickups.reduce(
    (total, pickup) => total + pickup.rate,
    0,
);

export const scoutTheFourEmperorsMarshallDTeach20261006: ScoutBanner = {
    id: "the-four-emperors-marshall-d-teach-20261006",
    name: "[2,800th Day Anniversary] Extreme Bounty Festival",
    bannerImg: "/scouts/the-four-emperors-marshall-d-teach-20261006.webp",
    startAt: "2026-09-24T14:00:00+09:00",
    endAt: "2026-10-06T13:59:59+09:00",
    pullOptions: {
        single: { pullCount: 1, diamondCost: 5 },
        multi: { pullCount: 11, diamondCost: 50 },
    },
    pickups,
    featuredCharacterId: "the-four-emperors-marshall-d-teach",
    rates: {
        pickup: totalPickupRate,
        bf: 2.9,
        "star-4": 3.9,
        "star-3": 35,
        "star-2": 58,
    },
};
