/* This file is generated by scripts/scout-importer/import.mjs. */

import type {
    ScoutBanner,
    ScoutPickup,
} from "./type";

const pickups = [
    {
        characterId: "the-four-emperors-monkey-d-luffy",
        rate: 0.02,
    },
    {
        characterId: "ama-no-murakumo-sword-kizaru",
        rate: 0.02,
    },
    {
        characterId: "flame-emperor-sabo",
        rate: 0.02,
    },
    {
        characterId: "legendary-hero-monkey-d-garp",
        rate: 0.02,
    },
    {
        characterId: "divine-departure-shanks",
        rate: 0.02,
    },
    {
        characterId: "awakened-form-rob-lucci",
        rate: 0.02,
    },
    {
        characterId: "seraphim-s-snake",
        rate: 0.02,
    },
    {
        characterId: "great-pirate-gol-d-roger",
        rate: 0.02,
    },
    {
        characterId: "great-pirate-edward-newgate",
        rate: 0.02,
    },
    {
        characterId: "blackbeard-pirates-kuzan",
        rate: 0.02,
    }
] satisfies readonly ScoutPickup[];

const totalPickupRate = pickups.reduce(
    (total, pickup) => total + pickup.rate,
    0,
);

export const scoutTheFourEmperorsMonkeyDLuffy20260917: ScoutBanner = {
    id: "the-four-emperors-monkey-d-luffy-20260917",
    name: "260 Million Downloads Celebration Ex",
    bannerImg: "/scouts/the-four-emperors-monkey-d-luffy-20260917.webp",
    startAt: "2026-09-08T14:00:00+09:00",
    endAt: "2026-09-17T10:59:59+09:00",
    pullOptions: {
        single: { pullCount: 1, diamondCost: 5 },
        multi: { pullCount: 11, diamondCost: 50 },
    },
    pickups,
    featuredCharacterId: "the-four-emperors-monkey-d-luffy",
    rates: {
        pickup: totalPickupRate,
        bf: 2.86,
        "star-4": 3.96,
        "star-3": 35,
        "star-2": 58,
    },
};
